== Briefcase
This section will give an overview of {product-short}'s Briefcase feature.

=== Navigating to Briefcase
Click btn:[Cloud Storage] -> btn:[Briefcase] to access the Briefcase tab.

It has

. A left sidebar.
. A list pane.
. A file preview pane.

To disable preview pane, click image:graphics/chevron-down.svg[down icon, width=20] at the top right hand corner and select the "No preview pane" option.

You can drag to change the width of the left pane.

=== Left Sidebar

The left pane contains a button to upload files, and lists folders.

Upload:: To upload files in Briefcase. 

Briefcase:: To view the uploaded files in Briefcase. 

Trash:: To view the deleted files.

Folders:: To create separate folders.

=== List pane

This pane displays the list of the uploaded files.

=== File Preview pane

When any file is selected, the preview is generated and displayed in this pane.

A toolbar displays the actions which can be taken on the selected file.

NOTE: The toolbar buttons become functional after user selects a file.

=== Uploading a file to Briefcase
. Click btn:[Cloud Storage] -> btn:[Briefcase].
ifdef::z9[]
. Click btn:[Upload]. It will open a file explorer.
endif::z9[]
ifdef::zcloud[]
. Click btn:[New] -> *Upload*. It will open a file explorer.
endif::zcloud[]
. In the file explorer, select the file to be uploaded and click btn:[Open].
+
NOTE: The upload button stays disabled till a file upload is completed.
+
. Upon successful file upload, the file will be displayed in the list pane.

IMPORTANT: Navigating away from the Briefcase tab to any other tab, while the file upload is in progress, will cancel the upload.

IMPORTANT: The maximum file size allowed for upload is the same which is set by the Administrator for uploading the attachments in Mail.

=== Downloading a file from Briefcase
. Click btn:[Cloud Storage] -> btn:[Briefcase].
. In the file list pane, select a file to be downloaded.
. Click on the btn:[Download] present in the toolbar above the preview pane.
. From the file browser window, choose a location to save the file.
. The file is downloaded at the specified location.
. The download option is also available in right-click context menu of the file, as well as on mouse hover on a file.

=== Previewing a Briefcase file
. Click btn:[Cloud Storage] -> btn:[Briefcase].
. In the file list pane, select a file for preview.
. Preview is generated in the preview pane.

NOTE: If preview is not supported for the file type, then the preview will not be generated and an option to download the file will be displayed.

IMPORTANT: If multiple files are selected, then the count of the selected files is displayed in the preview pane.


=== Sorting Briefcase Files
Briefcase files can be sorted according to *Date*, *Name*, *Starred*. The default sorting is based on *Date*.

==== Sorting files by Name
. Click btn:[Cloud Storage] -> btn:[Briefcase].
. From the toolbar above the file list pane, click image:graphics/chevron-down.svg[down icon, width=20].
. Select *Name*.
. Clicking image:graphics/arrow-down-briefcase.svg[down arrow, width=20] or image:graphics/arrow-up-briefcase.svg[up arrow, width=20] will apply the sorting in ascending or descending order.

==== Sorting files by Starred
. Click btn:[Cloud Storage] -> btn:[Briefcase].
. From the toolbar above the file list pane, click image:graphics/chevron-down.svg[plus icon, width=20].
. Select *Starred*.
. Clicking image:graphics/arrow-down-briefcase.svg[down arrow, width=20] or image:graphics/arrow-up-briefcase.svg[up arrow, width=20] will apply the sorting in ascending or descending order.

==== Sorting files by Date
. Click btn:[Cloud Storage] -> btn:[Briefcase].
. From the toolbar above the file list pane, click image:graphics/chevron-down.svg[plus icon, width=20].
. Select *Date*.
. Clicking image:graphics/arrow-down-briefcase.svg[down arrow, width=20] or image:graphics/arrow-up-briefcase.svg[up arrow, width=20] will apply the sorting in ascending or descending order.


=== Briefcase Search
You can type the name of the file or extension of the file in the Search box at the top of the Briefcase page.

==== Briefcase Search box
. Click btn:[Cloud Storage] -> btn:[Briefcase].
. Type few words of the file or file extension and click image:graphics/search.svg[magnifying glass icon, width=20].
. A new search tab will display the files matching the search criterion.

IMPORTANT: Advanced Search option is not available for Briefcase.


=== Creating Briefcase Folders
New folders can be created to organize files.

. Click btn:[Cloud Storage] -> btn:[Briefcase]
. In the left sidebar, hover over the *Folders* and click image:graphics/plus.svg[plus icon, width=20].
. Enter the name for the new folder and press kbd:[Enter].
. The folder will be created and appear under *Folders*.

==== Creating Subfolders
Subfolders can be created under *Briefcase*.

. Click btn:[Cloud Storage] -> btn:[Briefcase].
. In the left sidebar, right-click on *Briefcase* or any other folder, and then click on "Create subfolder" option.
. Enter the name for the subfolder and press kbd:[Enter].
. The subfolder will be created and appear under its parent folder.


=== Share Briefcase Folders
The default Briefcase folder or any newly created folder appearing under *Folders* can be shared with the other users.

==== Steps to share a folder
. Click btn:[Cloud Storage] -> btn:[Briefcase].
. In the left pane, right-click a folder to share.
. From the context menu, choose *Share*.
. Choose appropriate permission from *Sharing Permissions* dropdown.
+
View:: Users can view all files under the shared folder but cannot make any changes to that folder.

View, edit, add and remove:: Users have permission to view and edit the contents of a folder, create new subfolders, upload files, and delete items from the folder.

View, edit, add, remove, and administer:: Users have permission to view and edit the content of a shared folder, create new subfolders, upload files, delete items from the shared folder, and share the folder with others.

. Enter the email address(s) with whom you want to to share the folder.
. Click btn:[Save] for changes to take effect.

NOTE: The folders shared with the user, will appear under *Shared Folders*

NOTE: If the folder is shared with *View* only permission, the Upload and Delete buttons are disabled.


=== Move Briefcase files
If custom folders are created, then Uploaded files can be moved from one folder to another.

==== Move files using drag and drop
. Click btn:[Cloud Storage] -> btn:[Briefcase].
. Select the file in list pane and drag it onto a folder in left pane and drop it.
. The file is moved to that folder.


==== Move files using Move option
. Click btn:[Cloud Storage] -> btn:[Briefcase].
. Select a file to be moved.
. Click the *Move* option in the toolbar above Preview Pane.
. Select the destination folder.
. The file is moved to that folder.
+
--
TIP: If there are a lot of folders, then a folder can be searched by typing the name in image:graphics/search.svg[magnifying glass icon, width=20].
--
+


=== Star a Briefcase file
This feature is like flagging the file so that it stands out and appears with a star in the file list.

==== Star from Right-click menu
. Click btn:[Cloud Storage] -> btn:[Briefcase].
. Right-click a file and select *Star* from the context menu. You may also mouse hover a file, and click the *Star* icon.
. A image:graphics/star.svg[star icon, width=20] will appear next to the file name.

==== Star from More menu
. Click btn:[Cloud Storage] -> btn:[Briefcase].
. Select a file.
. Click on *More* in the toolbar above the preview pane.
. Select *Star*.
. A image:graphics/star.svg[star icon, width=20] will appear next to the file name.


=== Unstar a Briefcase file
This feature removes the flag set for a file.

==== Unstar from right-click menu
. Click btn:[Cloud Storage] -> btn:[Briefcase].
. Right-click a file and select *Clear Star* from the context menu.
. A image:graphics/star.svg[star icon, width=20] will disappear for the file.


==== Unstar from More menu
. Click btn:[Cloud Storage] -> btn:[Briefcase].
. Select a file.
. Click on *More* in the toolbar above the preview pane.
. Select *Clear Star*.
. A image:graphics/star.svg[star icon, width=20] will disappear for the file.

=== Deleting a Briefcase file
A briefcase file can be deleted in two ways.

==== From Right-click menu
. Click btn:[Cloud Storage] -> btn:[Briefcase].
. Right-click on a file select *Delete*.
. The file is deleted and moved to the Trash folder.

==== Using Delete button    
. Click btn:[Cloud Storage] -> btn:[Briefcase].
. Select a file.
. Click btn:[Delete] in the toolbar above the preview pane.
. The file is deleted and moved to the Trash folder.


=== Move custom Briefcase folders/subfolders
If custom folders/subfolders are created, then those folders can be moved to other folders.

. Click btn:[Cloud Storage] -> btn:[Briefcase].
. Right-click on a folder/subfolder and select *Move folder* from the context menu.
. Select the destination folder.


=== Rename custom Briefcase folders/subfolders
. Click btn:[Cloud Storage] -> btn:[Briefcase].
. Right-click on a folder/subfolder and select *Rename* from the context menu.
. Type the new name for the folder/subfolder in the text box. 
. Press kbd:[Enter] to save.

TIP: If there are a lot of folders, then a folder can be searched by typing the name in image:graphics/search.svg[magnifying glass icon, width=20].

=== Attaching files from briefcase to email

IMPORTANT: This option will only be available when Briefcase feature is enabled for the user.

Files available in Briefcase can be attached to an Email.

. In the mail composer,  click image:graphics/paperclip.svg[width=20px] to open file attach options.
. Clicking **Attach files from Briefcase** brings up a file explorer.
. Navigate to the folder, select the file to attach and click **Attach**.
The selected file now appears as an attachment.

IMPORTANT: Inline images cannot be added from Briefcase.

=== Uploading files from email to briefcase 
Files from the email can be directly uploaded to Briefcase.

. Select the email which has attachments.
. In the reading pane, hover over the file and click image:graphics/briefcase.svg[briefcase icon, width=20px].
. In the file explorer, select a folder and click btn:[Save].
. Upon successful file upload, a message will be displayed *Attachment added to Briefcase*.
