=== Email Search Box
You can type several phrases in the Search box at the top of the <<mail-overview.adoc#_email_pane, Email Pane>>. In addition to searching for different words and phrases, you can search in all the folders collectively or individually.

To search, type in your search word or phrase in the email search box and press kbd:[Enter].

=== Email Search Location
To search in a specific folder, choose the folder name from the drop-down beside the <<Email Search Box>>.

After you have chosen the folder, type in your search word or phrase in the email search box and press kbd:[Enter].

=== Advanced Search
Choose **Advanced Search** from <<Email Search Location>> drop-down.
Fields listed here help refine your search further.

. Choose a folder from the **Search-In** field.
. Typing an email address in the **From** field focuses your search on all emails sent *from* that address.
. Similarly, typing an email address in the *To* field focuses your search on all emails sent *to* that address.
. Type a few words in the **Subject** line, to search emails with these words in their subject line.
. Type a few words contained in the body of the email in *Contains** field.
Enclose the searched text within quotes to search them as a phrase.
. Specify a date in the **Date** field.
. Check the boxes **Has attachment** or **Has image** if the email you are looking for has an image or an attachment.

NOTE: None of the above search criteria is mandatory.
However, adding more criteria reduces search time and refines the search results further.