== Settings
Settings in {product-short} have multiple features like changing signatures, creating filters, and mail reading behavior being a few among many.

=== General
This section deals with storage, date & time format, and the default app version which you see after login.

==== Storage
This section of the {modern-client} displays the storage and the allocated space that you are using on the {product-short} server.

==== Date & Time
This section manages the date and time format used throughout the {modern-client}.

===== Date Format
There are 4 date formats to choose from:

mm/dd/yyyy:: January 9, 2021 appears as *01/09/2021*.
dd/mm/yyyy:: January 9, 2021 appears as *09/01/2021*.
yyyy-mm-dd:: January 9, 2021 appears as *2021-01-09*.
dd-mmm-yy:: January 9, 2021 appears as *09-Jan-21*.

===== Time Format
There are 4 date formats to choose from:

h:mm:: The time 9:21 AM appears as *9:21 AM*.
hh:mm:: The time 9:21 AM appears as *09:21 AM*.
H:MM:: The time 9:21 AM appears as *9:21*.
HH:MM:: The time 9:21 AM appears as *09:21*.

==== {product-short} Version
Here you choose the {product-short} version you want to use.

Modern:: Choose this option to use the {modern-client}.
Classic:: Choose this option to use the {web-client}.