=== Account Settings

==== Add an Account
The Modern Web App can help you manage emails that you receive on other email addresses.
Through the Modern Web App you can send and receive emails using these email addresses.

. Select image:graphics/cog.svg[cog icon, width=20] -> *Settings*.
. Click *Accounts* in the left pane and choose image:graphics/plus.svg[width=20] *Add an account*.
. Enter your email address in the *Email Address* field.
. Enter the password for this email address in the *Password* field.
+
--
TIP: You may need to generate an app password, if your email provider mandates it.
Once generated, use the app password in the *Password* field.
--
+
. Choose an account type, from *POP* or *IMAP*, that you want to configure with the Modern Web App.
. Enter the username associated with this email address.
. Type the mail server name in *Mail Server* field.
Please check with your email provider for this information.

==== Change the name on your {product-short} account
You can choose what name people see when you send them an email.

. Select image:graphics/cog.svg[cog icon, width=20] -> *Settings*.
. Click *Accounts* in the left pane and choose an account from the right pane.
. Under *Your Name* type in a name that you want people to see when they receive your emails.
. At the bottom of the page, click btn:[Save].

==== Change your {product-short} Mailbox Name
If you have multiple email accounts configured through {product-short}, you may want to differentiate them.

. Select image:graphics/cog.svg[cog icon, width=20] -> *Settings*.
. Click *Accounts* in the left pane and choose an account from the right pane.
. Under *Description* type in a name for this account.
. At the bottom of the page, click btn:[Save].

==== Add a Persona
A persona helps you create a separate email identity to manage different types of email.
E.g., you can create a persona for your business email and one for your personal email.
By using a persona, you can specify a different *From* address or a *Reply-To* address for emails sent using that persona.
All outgoing email displays the email address of the persona that you are using.

. Select image:graphics/cog.svg[cog icon, width=20] -> *Settings*.
. Click *Accounts* in the left pane and choose image:graphics/plus.svg[width=20] *Add a persona*.
. Type a name under *Persona Name* to identify your persona.
. Choose an account from *Send from this account*.
. Type in a name which recipients see as the sender's name.
+
--
TIP: If this box is empty, persona will use From name of the sending account.
--
+
. Check *Enable* against *Direct replies to a different email address*, to receive replies on a different email address.
.. Enter a _Reply-to address_.
.. Type in a _Reply-to name_.
. Click *Add Persona* to create this persona.

==== Two-factor Authentication

===== 2FA Enabled
If two-factor authentication is only enabled but not enforced, you have the option to set up two-factor authentication at your convenience.
Application usage is not affected.

. Select image:graphics/cog.svg[cog icon, width=20] -> *Settings*.
. Click *Accounts* in the left pane and choose an account from the right pane to enable 2FA.
. Click btn:[Set up two-factor authentication].
. Enter your password when prompted.
. Install an authentication app on your mobile device.
Check https://wiki.zimbra.com/wiki/TOTPApps[supported apps].
. Once installed, configure it on your smartphone.
. Click *Next* on the {product-short} screen to begin the process of adding this account to the authentication app.
. On the authenticator app, enter the code generated on the {product-short} screen.
. Click *Next*. 
. Enter the code generated by your authenticator app and click *Verify* to complete the two-factor authentication setup.

===== Login Screen
Once set up, {product-short} prompts you to enter a code as part of every login.
Enter the code displayed in your authenticator app at that time and click *Verify*.

===== Adding Trusted Devices
Once you have set up 2FA, {product-short} requires a code from the authenticator app on each login.
You can set a device as a trusted device, so you do not have to enter an authentication code. 

. Launch {product-short}.
. Enter an authorized username and password.
. Check the box, *Always trust this device*.
. Enter the two-factor authentication code from the authentication app.
. Click *Verify* to login.

Next time when logging in from this device, you do not need to enter the authentication code.

===== Removing Trusted Devices
When you remove a device from the list of trusted devices, {product-short} prompts you to enter the authentication code next time you attempt to login using that device.
To remove a device from the list of trusted devices, login from the device you wish to remove from the trusted devices' list.

. Select image:graphics/cog.svg[cog icon, width=20] -> *Settings*.
. Click *Accounts* in the left pane and choose an account from the right pane.
. Scroll down to *Two-factor authentication* segment.
. Click *Don't trust this device*.

TIP: To remove all your devices from the list of trusted devices, *except* the one you have logged in from, click *Don't trust all other devices*.

{product-short} removes the target device from the list of trusted devices with immediate effect.

===== One-time codes

One-time codes are a set of ten codes used to complete the two-factor authentication when you do not have access to the authentication app.
You can use each of these unique codes only once.
{product-short} has an option to regenerate a new set of codes.
We recommend that you copy and keep the codes in a safe place on the first available opportunity.

IMPORTANT: You cannot log in to {product-short} if you do not have the codes or access to the authenticator app.

===== Generate One-time Codes
. Select image:graphics/cog.svg[cog icon, width=20] -> *Settings*.
. Click *Accounts* in the left pane and choose an account from the right pane.
. Scroll down to *Two-factor authentication* segment.
. Click *10 unused codes*.
. Click *Copy to clipboard* to copy the codes, paste in a text file, and save the file in a safe place.

NOTE: Once clicked, *Copy to clipboard* changes to *Copied*. The codes can be copied again by clicking *Copied*.

==== Adding an App Passcode
Most desktop email programs have no way to ask for or enter the unique code to complete the two-factor authentication. {product-short} helps you generate a passcode that you can use instead of your _real_ account password when configuring your email program.

. Select image:graphics/cog.svg[cog icon, width=20] -> *Settings*.
. Click *Accounts* in the left pane and choose an account from the right pane.
. Scroll down to *Two-factor authentication* segment.
. Click *Add a passcode*.
. Enter a name that helps you identify the app password you create and click *Next*.
. Copy the code, paste in a text file, and save the file in a safe place.
You need this code when configuring your email program.
. Enter this passcode instead of your account password when configuring an email client with {product-short}.

===== Removing an App Passcode

. Select image:graphics/cog.svg[cog icon, width=20] -> *Settings*.
. Click *Accounts* in the left pane and choose an account from the right pane.
. Scroll down to *Two-factor authentication* segment.
. Hover over the email application you want to remove.
. Click image:graphics/close.svg[close icon, width=20] to remove the targeted application.

===== Disable 2FA

. Select image:graphics/cog.svg[cog icon, width=20] -> *Settings*.
. Click *Accounts* in the left pane and choose an account from the right pane.
. Scroll down to *Two-factor authentication* segment.
. Click the button *Remove two-factor authentication*.

You can now log in without the need to enter an authentication code.

IMPORTANT: You can disable 2FA only if the administrator has allowed this option for you.

==== Reply-to Address
You can receive replies to your emails on a different address using this feature.

. Select image:graphics/cog.svg[cog icon, width=20] -> *Settings*.
. Click *Accounts* in the left pane and choose an account from the right pane.
. Scroll down to *Reply-to-Address* segment.
. Check the box *Receive replies to your sent emails at a different address*.
. Enter an email address where you'd like to receive replies for your emails.
. Type in a name corresponding to the above email address.
. At the bottom of the page, click btn:[Save].

==== Access your emails elsewhere
You can set a forwarding address in {product-short}. {product-short} forwards all your emails to the address specified here.

. Select image:graphics/cog.svg[cog icon, width=20] -> *Settings*.
. Click *Accounts* in the left pane and choose an account from the right pane.
. Scroll down to *Access your mail elsewhere* segment.
. Check the box *Forward: {product-short} forwards all your emails to the specified address so that you can check it there*.
. Enter an email address where you'd like to forward your emails.
. From the drop-down, choose if {product-short} should keep a copy of the email received.
+
Store and Forward:: {product-short} keeps a copy of the email before forwarding it to the specified address.
Delete and Forward:: {product-short} deletes the email after forwarding it to the specified address.

. At the bottom of the page, click btn:[Save].

ifdef::Desktop_app[]
==== Import PST File
NOTE: This feature is available only on the {product-short} desktop app for Windows.

When you add an email account to Outlook, {product-short} stores a  local copy of your email messages, calendar information, contacts, and tasks on your computer.
Some account types store their information in Outlook Data Files (`.pst` files).

These `PST` files can be imported into {product-short} desktop application to the <<mail-localstorage.adoc#_local_storage, Local Storage>> folder.
Below instructions assume that you have already copied the `PST` file to your computer.
To export or backup email, contacts, and calendar to `PST` file refer to https://support.office.com/en-us/article/back-up-your-email-e5845b0b-1aeb-424f-924c-aa1c33b18833[Back up your email].

. Select image:graphics/cog.svg[cog icon, width=20] -> *Settings*.
. Click *Accounts* in the left pane and choose an account from the right pane.
. Scroll down to the section *Import from Outlook (.pst file)*.
. Click *Choose .pst file*.
. Browse through and select the `PST` to import.
. The `PST` file name appears beside the *Choose .pst file* button.
. Click *Import*.

NOTE: While {product-short} is importing `PST` the local folder cannot be accessed.
You may continue to use *Mail*, but do not use *Calendar* and *Contacts*. {product-short} notifies you once the import is complete.
endif::Desktop_app[]

==== Export
You can export all your emails, contacts, and calendars as a `.tgz` file.
To export individual folders, emails, contacts, or calendars, right-click those items and choose *Export* from the context menu.

. Select image:graphics/cog.svg[cog icon, width=20] -> *Settings*.
. Click *Accounts* in the left pane and choose an account from the right pane.
. Scroll down to *Export* and click btn:[Export].

==== Import
You can import all your emails, contacts, and calendars from a `.tgz` file.

. Select image:graphics/cog.svg[cog icon, width=20] -> *Settings*.
. Click *Accounts* in the left pane and choose an account from the right pane.
. Scroll down to *Import* and click btn:[Import].

==== Mobile or Desktop Configuration
IMAP, CalDav, and CardDav are an open set of rules for synchronizing your emails, contacts, calendars, and tasks with mobile or desktop devices.
{product-short} creates mobile profiles which you can download, configure, and sync your mobile devices.

Android OS natively (without the help of external apps) supports IMAP for managing email; however, CalDAV and CardDAV require installation of apps like OpenSync.
Mac and iOS have provisions for working with CalDAV and cardDAV; hence, you do not need any Mac or iOS app to work with them.

This section explains how to export profiles.
To import these profiles to your mobile devices, you may want to look at below help articles:

===== Export Profiles
There are five profiles available to download and sync with devices that support this.

Email, Calendar, and Tasks, Contacts:: This profile syncs Email, Calendar, Tasks, and Contacts on mobile devices with {product-short}.
Calendar and Tasks, Contacts:: This profile syncs only Calendar, Tasks, and Contacts on mobile devices, with {product-short}; it does not sync emails.
Calendar and Tasks:: This profile syncs only Calendar and Tasks on mobile devices, with {product-short}; it does not sync emails and contacts.
Contacts:: This profile syncs only contacts on mobile devices, with {product-short}; it does not sync emails, calendars, and tasks.
Email:: This profile syncs only emails on mobile devices, with {product-short}; it does not sync contacts, calendars, and tasks.

. Select image:graphics/cog.svg[cog icon, width=20] -> *Settings*.
. Click *Accounts* in the left pane and choose an account from the right pane.
. Scroll down to *Mobile or Desktop configuration* segment.
. Choose one of the profiles from the drop-down and click *Download*.
. Choose a location to save the downloaded file. {product-short} requires this file when importing profiles to <<Import profiles to iOS, iOS>> or <<Import profiles to Android, Android>> devices.


===== Import profiles to iOS
IMAP:: https://support.apple.com/en-in/HT201320
CalDAV:: https://support.apple.com/en-in/guide/iphone/iph3d1110d4/ios
CardDAV:: https://support.apple.com/en-in/guide/iphone/iph14a87326/ios

===== Import profiles to Android

Since Android -- without external apps -- supports IMAP only, you may need to check the instructions specific to the app you use for CardDAV and CalDAV.

==== ActiveSync

. To setup ActiveSync on Outlook, refer to this guide :- https://wiki.zimbra.com/wiki/Exchange_ActiveSync%28EAS%29_Outlook_2013

. To setup ActiveSync on Apple Devices, refer to this guide :- https://wiki.zimbra.com/wiki/Zimbra_Mobile_Installation_and_Setup_for_iPhone
