=== Out of Office settings
With {product-short}, you can send out-of-office replies for any duration you specify.

. Select image:graphics/cog.svg[cog icon, width=20] -> *Settings*.
. Click *Out Of Office* in the left pane.
. Check the box *Enable automatic response during these dates (inclusive)*.
. Specify a *From* date.
. Specify an *Until* date.
** If the until date is uncertain, check the box *No end date*.
. Type a response that you'd want to send while you are out of office.
** Test out the response by clicking btn:[Send sample copy to me].

==== Out of Office replies for external senders
You can choose if you want to send an out-of-office response to senders who are not in your organisation (external senders).

Against *External Senders* there are three options in the dropdown.

Send standard automatic response:: Choose this option to send the same response specified above, to external senders.
Send external automatic response:: Choose this option to bring up a text box and type a separate response to external senders.
Click btn:[Send sample copy to me] to test out this response.
Do not send automatic response:: Choose this option to avoid sending out-of-office response to external senders.