=== Calendar and Reminder Settings
This setting controls,

* default calendar to create events in,
* the day when a week starts,
* time when a typical workday starts and ends,
* calendar events time zone,
* if the calendar, when shared, a delegate can manage through a mobile device, and
* the email address to send event reminders.

==== General Calendar Settings
. Select image:graphics/cog.svg[cog icon, width=20] -> *Settings*.
. Click *Calendar and Reminder Settings* in the left pane.
. Choose a *Default Calendar* from the drop-down.
If you have not <<calendar-manage-calendars.adoc#_add_calendars, added a calendar>>, the drop-down does not have any other entries.
. Choose a *Start of Week* from the drop-down.
. Choose a time when your workday starts from *Start of Workday* drop-down.
. Specify a time when your workday ends from the *End of Workday* drop-down.
. Set a time zone for your workdays under *Workday Time Zone*.
.. Alternatively, check the box *Show timezones for start and end times* to set time zones on the fly.
. Check the box *Enable delegation for CALDav clients* against *Sharing* to allow delegated users to manage your <<calendar-manage-calendars.adoc#_share_a_calendar, shared calendars>> using their mobile devices.

==== Event Reminders
You can specify an email address to receive event reminders.

. Select image:graphics/cog.svg[cog icon, width=20] -> *Settings*.
. Click *Calendar and Reminder Settings* in the left pane.
. Enter the email address in *Send reminders by email to* field to send event reminders to that email address.
. Check the box *Show Browser Notifications* to receive event reminders via browser notifications.
. Specify a *Default Reminder Time* before which to receive event reminders.
. Check the box to enable *Show Reminders for Past-Due Events* to receive reminders for events that are past due.
This way, you receive reminders for events that you might have unknowingly missed.

==== Free Busy Permission
You can use this setting to control who can see when you are free or busy.
Event organizers can click on btn:[Show Availability] when <<calendar-manage-events.adoc#_schedule_an_event, scheduling an event>> to see when you are available for a meeting.

Choose an option from the dropdown.

Everyone:: All organizers can view the time when you are free or busy.
Internal users only:: Your Free/Busy information is available to all users within your organization.
Internal users on my domain only:: Your Free/Busy information is available only to users within your domain. Users in your organization who have email addresses on another domain can not view your Free/Busy information.
These internal users only:: Enter email addresses, below this dropdown, of users who can view your free/busy information. Click btn:[Add] after entering each email address.
The field *Enter an email address* is active only for this option.
None:: Your free/busy information is hidden from everyone, without exception.
