=== Account Recovery
We always recommend adding an alternate email address to get account recovery instructions if you forget the login credentials to your email account.

. Select image:graphics/cog.svg[cog icon, width=20] -> *Settings*.
. Click *Account Recovery* in the left pane and click *Add Recovery Email*.
. Enter an email address where you would like to receive account recovery instructions.
. Click *Continue*.
. You receive a code on this alternate email address.
Check your email and copy the verification code.
. Paste in the above prompt to verify the alternate email address.

==== Password reset using "Forgot Password" feature

. On the login page, click "Forgot Password?".
. Enter the email address for which password needs to be reset and click btn:[Submit].
. Click btn:[Request Code]. The code is sent to alternate email address provided in <<Account Recovery>> section.
. Copy the code and paste in the above prompt. Click btn:[Verify Code].
. Click btn:[Reset Password] and specify the new password for the user. Click btn:[Submit]. 
. On successful password reset, "Password Reset Success!" is displayed on the screen.
. Click btn:[Back to sign in] to login with the new password for the user.
