=== Account Recovery
We always recommend adding an alternate email address to get account recovery instructions if you forget the login credentials to your email account.

. Select image:graphics/cog.svg[cog icon, width=20] -> *Settings*.
. Click *Account Recovery* in the left pane and click *Add Recovery Email*.
. Enter an email address where you would like to receive account recovery instructions.
. Click *Continue*.
. You receive a code on this alternate email address.
Check your email and copy the verification code.
. Paste in the above prompt to verify the alternate email address.

=== Signatures
With {product-name}, you can have two default signatures per account, plus additionals that you may choose to apply.

. Select image:graphics/cog.svg[cog icon, width=20] -> *Settings*.
. Click *Signatures* in the left pane.
.. To set a signature to be used while composing an email, draft your signature against the *Standard signature* field.
.. To set a signature to be used while replying to or forwarding an email, draft your signature against the *Reply or forward signature* field.
// . To create additional signatures, click *Add a signature*.
// . Enter a name for this sign to differentiate it from the rest.
// . To remove this signature, click *Remove signature* against the signature's name.

=== Filters -- Automate management of your email
{product-name} allows you to create filters through which you can sort incoming messages into folders by defining some rules for better sorting.

==== Create New Filter

. Select image:graphics/cog.svg[cog icon, width=20] -> *Settings*.
. Click *Filters* in the left pane.
. Click *Add* to create a new filter.
. Set a *Filter Name*.
. There are two filter editors -- Basic and Advanced.
By default, when creating a new filter *Basic* editor opens.

{product-name} takes these actions when it encounters mails that meet the defined criteria.

Move to folder:: You can move the filtered email to either *Junk* or *Trash*
Mark as read:: Leave the message in the inbox but mark it as read.
Permanently delete:: Discard the email, so it does not appear in the *Trash* folder.
Forward to:: Redirect the email to another email address.
Star:: Flag the email so that it stands out and appears with a star in the email list.
Tag With:: Mark an email with tags that you have created.
For more information check <<mail-overview.adoc#_tags, tags>>.

===== Basic
In the basic editor, you can specify only one action to affect emails that meet the filter criteria.
E.g., you can only mark it read _or_ move it to trash; you can't do both.
To perform multiple actions on emails matching specific criteria, check <<Advanced, advanced mode>>.

. Choose if the incoming mails have to meet *any* one or *all* of the defined criteria.
. Define the conditions that an email has to meet for the defined action to take effect.
. Under *Then* choose what happens with the filtered email.
You can choose only one action.

===== Advanced
In the advanced editor, you can specify multiple actions to affect emails that meet the filter criteria.
E.g., you can mark it read _and_ move it to trash.

. Click *Switch to advanced*.
. Choose if the incoming mails have to meet *any* one or *all* of the defined criteria.
. Define the conditions that an email has to meet for the defined action to take effect.
** To add more conditions, click *+ Add a condition*.
. Under *Then* choose what happens with the filtered email.
You can choose only one action.
** To add more actions click *+ Add an action*

IMPORTANT: *And do not process additional filters* check-box stops other filters from running on a message which meets the criteria for multiple filters.

==== Managing Filters
. Select image:graphics/cog.svg[cog icon, width=20] -> *Settings*.
. Click *Filters* in the left pane.
. The right pane lists all the filters that you have created so far.
.. Click and drag image:graphics/drag.svg[2 horizontal bars icon, width=20] to raise or lower the filter priority.
.. Check or uncheck a filter to enable or disable it.
.. Click image:graphics/ellipsis-h.svg[3 dots menu icon, width=20] against a filter to bring up options like *Details*, *Run*, *Edit*, and *Delete*.
+
Details:: Lists the conditions for an email to meet and the action to take when an email meets the filter criteria.
Run:: Choose an account and then folder(s) on which to run the filter.
Edit:: Opens the appropriate editor -- *Basic* or *Advanced* -- to edit a filter.
Delete:: Prompts a confirmation dialog before deleting a filter.

=== Block and Allow senders
You can block messages from specific email addresses or domains from reaching your inbox; you can also allow specific email addresses and domains, so their emails reach you every time.
When you add an email address or domain to your blocked senders' list, {product-name} blocks all messages from that sender.

==== Block senders from sending you email

. Select image:graphics/cog.svg[cog icon, width=20] -> *Settings*.
. Click *Blocked and Allowed Senders* in the left pane.
. Under *Blocked Senders and Domains*, enter the email address or domain that you want to block and click *Block*.

IMPORTANT: {product-name} removes emails by blocked senders from the server; they do not appear in either *Junk* or *Trash*. 

==== Allow senders
If you want to remove someone from the blocked senders' list, follow the instructions below.

. Select image:graphics/cog.svg[cog icon, width=20] -> *Settings*.
. Click *Blocked and Allowed Senders* in the left pane.
. Under *Blocked Senders and Domains*, select the email address or domain that you want to unblock and click *Remove*.

==== Stop messages from going into your Junk Email folder
Messages from these senders and domains bypass spam filters and are always delivered.

. Select image:graphics/cog.svg[cog icon, width=20] -> *Settings*.
. Click *Blocked and Allowed Senders* in the left pane.
. Under *Allowed Senders and Domains*, enter the email address or domain that you want to receive emails from and click *Allow*.

IMPORTANT: If the same email address is in the whitelist and the blacklist, whitelisting takes precedence.

=== Offline mode
With {product-name}, you can work offline to avoid incurring cellular data charges or to stop {product-name} from attempting to send and receive messages over a slow network connection.
You can manage and compose mail, contacts, and appointments when you are offline.
The changes sync when you are back online.

. Select image:graphics/cog.svg[cog icon, width=20] -> *Settings*.
. Click *Offline Mode* in the left pane.
+
Enable offline mode:: Copies of recent items are saved locally.
They are synchronized with the server when {product-name} goes online.
Disable offline mode:: {product-name} is online, and all changes synchronize in real-time.

=== Security and Activity
This setting enables viewing of emails and shows the list of devices where {product-name} is open with your credentials.
You have the option to sign out from all other instances except this one.

==== Security

. Select image:graphics/cog.svg[cog icon, width=20] -> *Settings*.
. Click *Security and Activity* in the left pane.
.. To block images from appearing everywhere choose *Never by default*.
.. To block images from appearing only in *Junk* folder choose *Always, except in Junk folder*.

==== Activity
. Select image:graphics/cog.svg[cog icon, width=20] -> *Settings*.
. Click *Security and Activity* in the left pane.
. Click *Sign out* against sessions that you are no longer using or you don't recognize.

=== Calendar and Reminder Settings
This setting controls,

* default calendar to create events in,
* the day when a week starts,
* time when a typical workday starts and ends,
* calendar events time zone,
* if the calendar, when shared, a delegate can manage through a mobile device, and
* the email address to send event reminders.

==== General Calendar Settings
. Select image:graphics/cog.svg[cog icon, width=20] -> *Settings*.
. Click *Calendar and Reminder Settings* in the left pane.
. Choose a *Default Calendar* from the drop-down.
If you have not <<calendars-manage-calendars.adoc#_add_calendars, added a calendar>>, the drop-down does not have any other entries.
. Choose a *Start of Week* from the drop-down.
. Choose a time when your workday starts from *Start of Workday* drop-down.
. Specify a time when your workday ends from the *End of Workday* drop-down.
. Set a time zone for your workdays under *Workday Time Zone*.
.. Alternatively, check the box *Show timezones for start and end times* to set time zones on the fly.
. Check the box *Enable delegation for CALDav clients* against *Sharing* to allow delegated users to manage your <<calendar-manage-calendars.adoc#_share_a_calendar, shared calendars>> using their mobile devices.

==== Event Reminders
You can specify an email address to receive event reminders.

. Select image:graphics/cog.svg[cog icon, width=20] -> *Settings*.
. Click *Calendar and Reminder Settings* in the left pane.
. Enter the email address in *Send reminders by email to* field to send event reminders to that email address.
. Check the box *Show Browser Notifications* to receive event reminders via browser notifications.
. Specify a *Default Reminder Time* before which to receive event reminders.
. Check the box to enable *Show Reminders for Past-Due Events* to receive reminders for events that are past due.
This way, you receive reminders for events that you might have unknowingly missed.