ifdef::zcloud[]
=== Zulip
Zulip is a group chat app that helps you connect to other users in your organization and quickly initiate conversations. Once your administrator configures Zulip, you can see if other users in your organization are online, launch a private chat with users and connect to public streams. For more detailed information on Zulip’s features, please refer to https://zulip.com/help/[user documentation].

==== Accessing Zulip Tab

. Click [ *Chat* ] tab.
. Click [ *Zulip* ]

You will see a list of all the users in the organization on the right side. *Streams* determine who gets a message. *Topics* tell you what the message is about. *Streams* and other messaging options are displayed on the left side. Messages with the same stream and topic are shown together as a conversational thread in the center.

==== Checking User Presence and Sending Direct Messages
You can check the active / inactive status of users in your contacts, calendar items, or email conversations. From there, you can easily start a direct message conversation with that user.

. Hover over a name / email in the address bar of a sent or received email message or draft, or in the Invitees section of a calendar item.
. Click on the *Zulip chat* option.

A quick chat window within the {modern-client} will be opened.

NOTE: The quick chat window only supports basic text messages. You can navigate to the Zulip tab for more options like text with rich font, send attachments, start Jitsi video call and view status message set by the users.

==== Checking and Replying Missed Messages

In case of missed messages in chat, an email with subject *Zulip missed messages* is sent. The email will contain the missed chat message and option to *Reply in zulip* at the end of the email.

Clicking on *Reply in zulip* will open chat window in Zulip tab.

=== Zulip on Mobile

Zulip Chat Application is supported on Android and iOS platforms. The app can be downloaded from Google Playstore and App Store.

You can download the App from:

* Android - https://play.google.com/store/apps/details?id=com.zulipmobile&hl=en_IN&gl=US
* Apple - https://apps.apple.com/us/app/zulip/id1203036395

==== Installing the app

Zulip Mobile app is available for download at the Play store and App Store.

. Launch Play Store / Apple Store on your device.
. Search for "Zulip"
. Tap on the app.
. Tap *Install*.

After the app is successfully installed, an icon of the app is created on the home screen of your device.

==== Setting up the App:

. Open the Zulip app. Specify the organization's Zulip server URL in the text box. For e.g. `https://myzimbra.server.com`.
. Tap *Enter*.
. Enter your username in the *Email* field.
. Enter your password in the *Password* field.
. Tap *Log in* to login.

Upon successful authentication, the user will be logged into his Zulip chat account. 

* At the top of the screen, users will have an option to check all messages, starred messages, mentions and search.

* At the bottom of the screen, users can access all unread messages, Streams, Direct Messages, Settings and Profile.

endif::zcloud[]
