=== Email Search Box
You can type several phrases in the Search box at the top of the <<mail-overview.adoc#_e_mail_pane, E-mail Pane>>. In addition to searching for different words and phrases, you can search in all the folders collectively or individually.

To search, type in your search word or phrase in the e-mail search box and press kbd:[Enter].

=== Email Search Location
To search in a specific folder, choose the folder name from the drop-down beside the <<E-mail Search Box>>.

After you have chosen the folder, type in your search word or phrase in the e-mail search box and press kbd:[Enter].

=== Advanced Search
Choose **Advanced Search** from <<E-mail Search Location>> drop-down. Fields listed here help refine your search further.

1. Choose a folder from the **Search-In** field.
2. Typing an e-mail address in the **From** field focusses your search to all e-mails sent *from* that address.
3. Similarly, typing an e-mail address in the **To** field focusses your search to all e-mails sent *to* that address.
4. Type a few words in the **Subject** line, to search e-mails with these words in their subject line.
5. Type a few words contained in the body of the e-mail in **Contains** field.
6. Specify a date in the **Date** field.
7. Check the boxes **Has attachment** or **Has image** if the e-mail you are looking for has an image or an attachment.

NOTE: None of the above search criteria is mandatory. However, adding more criteria reduces search time and refines the search results further.