=== Known Issues

* In Offline mode, only partial (cached) Contacts and Calendar data is available to the users.
* When user is Offline and enters any text to search, the _Invalid Search, please try again_ error is displayed. When Offline, only the following keyword based search is supported - *from*, *to*, *cc*, *subject*, *in*, *has*, *date*. Other search parameters provided in the following list will be implemented as a part of product roadmap - http://docs.zimbra.com/desktop7/help/en_US/Search/query_language_description.htm.
* When a user sends a Signed/Encrypted email containing inline images added through the *Insert Images* option in the toolbar, the images are not displayed to the recipient.
* Users will not able to set the Zimbra Desktop app on Windows Operating System as the default mailto App.
* Share and Meeting action buttons don't appear on the emails when they are moved to a Local Folder.
* When users move a message which has a signature containing an image, from Inbox to a local folder, the image is lost.
* When the user replying to a Signed message which contains an inline image and changes the S/MIME setting to *Do not sign and encrypt*, an error is encountered and the mail is not sent.
* On Mac OS, when sending a Signed or Signed and Encrypted message, the email address of the sender is not displayed along with the message type. Only the message type like *Signed* or *Signed and Encrypted* gets displayed.
* Errors are encountered when a user who does not have a valid certificate tries to *Reply/Reply-All/Forward/* a Signed or Signed/Encrypted message.
* If a user creates contact with multiple email addresses and tries to upload the certificate which has only 1 matching email address in the contact, an error is encountered and the certificate upload fails. The workaround is to create a contact with a single email address matching the certificate.
