== ブリーフケース
ここでは、{product-short}のブリーフケース機能の概要を説明します。

=== ブリーフケースへの移動
btn:[クラウドストレージ] -> btn:[ブリーフケース]をクリックして、ブリーフケースタブにアクセスします。

画面には

. 左サイドバー
. リストペイン
. ファイルのプレビューウィンドウ
が表示されます。

プレビューウィンドウを無効にするには、右上のimage:graphics/chevron-down.svg[down icon, width=20] をクリックし、「プレビューウィンドウなし」を選択します。

ドラッグで左サイドバーの幅を変更できます。

=== 左サイドバー

左側のペインには、ファイルをアップロードするためのボタンとフォルダーのリストがあります。

アップロード:: ブリーフケースにファイルをアップロードします

ブリーフケース:: アップロードしたファイルをブリーフケースで表示します

ゴミ箱:: 削除されたファイルを表示します

フォルダー:: フォルダーを作成します

=== リストペイン

このペインには、アップロードされたファイルの一覧が表示されます。

=== ファイルのプレビューウィンドウ

ファイルが選択されると，プレビューが生成され，このウィンドウに表示されます。

ツールバーには、選択されたファイルに対して実行可能なアクションが表示されます。

NOTE: ツールバーのボタンは、ファイルを選択すると機能するようになります。

=== ブリーフケースへのファイルのアップロード
. btn:[クラウドストレージ] -> btn:[ブリーフケース] をクリックします。
ifdef::z9[]
. btn:[アップロード]をクリックします。ファイルエクスプローラーが開きます。
endif::z9[]
ifdef::zcloud[]
. btn:[新規] -> *アップロード*。ファイルエクスプローラーが開きます。
endif::zcloud[]
. ファイルエクスプローラーで、アップロードするファイルを選択し、btn:[開く]をクリックします。
+
NOTE: ファイルのアップロードが完了するまで、アップロードボタンは無効のままです。
+
. ファイルのアップロードに成功すると、リストペインにファイルが表示されます。

IMPORTANT: ファイルのアップロードが進行中にブリーフケースタブから他のタブに移動すると、アップロードがキャンセルされます。

IMPORTANT: アップロード可能な最大ファイルサイズは、管理者がメールで添付ファイルをアップロードする際に設定したものと同じです。

=== ブリーフケースからのファイルのダウンロード
. btn:[クラウドストレージ] -> btn:[ブリーフケース]をクリックします。
. ファイルリストペインで、ダウンロードするファイルを選択します。
. プレビューウィンドウの上のツールバーに表示されている btn:[ダウンロード] をクリックします。
. ファイルを保存する場所を選択します。
. 指定された場所にファイルがダウンロードされます。
. ダウンロードオプションは、ファイルを右クリックして表示されるコンテキストメニューや、ファイルの上にマウスを置いて表示されるメニューでも利用できます。

=== ブリーフケースファイルのプレビュー
. btn:[クラウドストレージ]->btn:[ブリーフケース]をクリックします。
. ファイルリストペインで、プレビューするファイルを選択します。
. プレビューウィンドウにプレビューが表示されます。

NOTE: プレビューがサポートされていないファイルタイプの場合は、プレビューは生成されず、ファイルをダウンロードするためのオプションが表示されます。

IMPORTANT: 複数のファイルが選択されている場合、選択されたファイルの数がプレビューペインに表示されます。


=== ブリーフケースのファイルの並び替え
ブリーフケースのファイルは、 *日時* 、 *名前* 、 *スター付き* に基づいて並び替えができます。デフォルトでは、 *日時* 順に並んでいます。

==== 名前順で並び替え
. btn:[クラウドストレージ]->btn:[ブリーフケース]をクリックします。
. ファイルリストペインの上のツールバーから、image:graphics/chevron-down.svg[down icon, width=20]をクリックします。
. *名前* を選択します。
. image:graphics/arrow-down-briefcase.svg[down arrow, width=20]または image:graphics/arrow-up-briefcase.svg[up arrow, width=20]をクリックすると、昇順または降順で並び替えが適用されます。

==== スター付き順で並び替え
. btn:[クラウドストレージ]->btn:[ブリーフケース]をクリックします。
. ファイル一覧ペインの上のツールバーから、image:graphics/chevron-down.svg[plus icon, width=20]をクリックします。
. *スター付き* を選択します。
. image:graphics/arrow-down-briefcase.svg[down arrow, width=20]または image:graphics/arrow-up-briefcase.svg[up arrow, width=20]をクリックすると、昇順または降順に並び替えが適用されます。

==== 日付順で並び替え
. btn:[クラウドストレージ]->btn:[ブリーフケース]をクリックします。
. ファイル一覧ペインの上のツールバーから、image:graphics/chevron-down.svg[plus icon, width=20]をクリックします。
. *日時* を選択します。
. image:graphics/arrow-down-briefcase.svg[down arrow, width=20]または image:graphics/arrow-up-briefcase.svg[up arrow, width=20]をクリックすると、昇順または降順に並び替えが適用されます。


=== ブリーフケースの検索
ブリーフケースページの上部にある検索ボックスに、ファイル名やファイルの拡張子を入力することができます。

==== ブリーフケースの検索ボックス
. btn:[クラウドストレージ]->btn:[ブリーフケース]をクリックします。
. ファイル名や拡張子をいくつか入力し、 image:graphics/search.svg[magnifying glass icon, width=20] をクリックします。
. 新しい検索タブに、検索条件に一致するファイルが表示されます。

IMPORTANT: 高度な検索オプションは、ブリーフケースでは利用できません。


=== ブリーフケースのフォルダーを作成
新しいフォルダーを作成してファイルを整理することができます。

. btn:[クラウドストレージ] -> btn:[ブリーフケース] をクリックします。
. 左サイドバーで、 *フォルダー* にカーソルを合わせ、image:graphics/plus.svg[plus icon, width=20]をクリックします。
. 新しいフォルダーの名前を入力し、kbd:[Enter]を押します。
. フォルダーが作成され、 *フォルダー* の下に表示されます。

==== サブフォルダーを作成
*ブリーフケース* の下にサブフォルダーを作成することができます。

. btn:[クラウドストレージ] -> btn:[ブリーフケース] をクリックします。
. 左サイドバーで、 *ブリーフケース* またはその他のフォルダーを右クリックし、「サブフォルダーを作成」をクリックします。
. サブフォルダーの名前を入力し、kbd:[Enter]キーを押します。
. サブフォルダーが作成され、その親フォルダーの下に表示されます。


=== ブリーフケースのフォルダーを共有
ブリーフケースのデフォルトのフォルダーや、 *フォルダー* の下に表示されるフォルダーは、他のユーザーと共有することができます。

==== フォルダーを共有する手順
. btn:[クラウドストレージ]->btn:[ブリーフケース]をクリックします。
. 左サイドバーから、共有するフォルダーを選んで右クリックします。
. コンテキストメニューから *共有* を選択します。
. *アクセス許可の共有* のドロップダウンから適切な権限を選択します。
+
表示:: ユーザーは、共有フォルダーの下にあるすべてのファイルを見ることができますが、そのフォルダーに変更を加えることはできません。

表示、編集、追加、削除:: ユーザーは、フォルダーの内容を表示・編集したり、新しいサブフォルダーを作成したり、ファイルをアップロードしたり、フォルダーからアイテムを削除する権限を持っています。

表示、編集、追加、削除、管理:: ユーザーは、共有フォルダーの内容を表示および編集し、新しいサブフォルダーを作成し、ファイルをアップロードし、共有フォルダーからアイテムを削除し、フォルダーを他の人と共有する権限を持っています。

. フォルダーを共有する相手のメールアドレスを入力します。
. btn:[保存]をクリックすると、変更が有効になります。

NOTE: ユーザーと共有されているフォルダーは、 *共有フォルダ* に表示されます。

NOTE: フォルダーが *表示* のみの権限で共有されている場合、 *アップロード* と *削除* のボタンは無効になります。


=== ブリーフケースファイルの移動
カスタムフォルダーを作成しておけば、アップロードしたファイルをあるフォルダーから別のフォルダーに移動させることができます。

==== ドラッグ＆ドロップによるファイル移動
. btn:[クラウドストレージ] -> btn:[ブリーフケース]をクリックします。
. リストペインでファイルを選択し、左サイドバーのフォルダーにドラッグ＆ドロップします。
. ファイルがそのフォルダーに移動します。


==== 移動オプションを使ったファイルの移動
. btn:[クラウドストレージ] -> btn:[ブリーフケース]をクリックします。
. 移動するファイルを選択します。
. プレビューペインの上にあるツールバーの *移動* オプションをクリックします。
. 移動先のフォルダーを選択します。
. ファイルがそのフォルダーに移動します。
+
--
TIP: フォルダーの数が多い場合は、image:graphics/search.svg[magnifying glass icon, width=20]にフォルダー名を入力して検索することができます。
--
+


=== ブリーフケースのファイルにスターをつける
この機能は、ファイルにフラグを立てるようなもので、ファイルリストにスターマークが表示されて目立ちます。

==== 右クリックメニューからスターをつける
. btn:[クラウドストレージ] -> btn:[ブリーフケース]をクリックします。
. ファイルを右クリックして、コンテキストメニューから *スターを付ける* を選択します。ファイルの上にマウスを置いて、 *スター* アイコンをクリックすることもできます。
. ファイル名のとなりに image:graphics/star.svg[star icon, width=20] が表示されます。

==== 「その他」メニューから「スター」を選択
. btn:[クラウドストレージ] -> btn:[ブリーフケース]をクリックします。
. ファイルを選択します。
. プレビューウィンドウの上にあるツールバーの *その他* をクリックします。
. *スターを付ける* を選択します。
. ファイル名のとなりに image:graphics/star.svg[star icon, width=20] が表示されます。


=== ブリーフケースのファイルのスターを外す
この機能は、ファイルに設定されているスターを削除します。

==== 右クリックメニューからスターを外す
. btn:[クラウドストレージ] -> btn:[ブリーフケース]をクリックします。
. ファイルを右クリックして、コンテキストメニューから *スターを外す* を選択します。
. ファイルに image:graphics/star.svg[star icon, width=20] が表示されなくなります。


==== 「その他」メニューから「スターを外す」を選択
. btn:[クラウドストレージ] -> btn:[ブリーフケース]をクリックします。
. ファイルを選択します。
. プレビューウィンドウの上にあるツールバーの *その他* をクリックします。
. *スターを外す* を選択します。
. ファイルに image:graphics/star.svg[star icon, width=20] が表示されなくなります。

=== ブリーフケースファイルの削除
ブリーフケースのファイルは、2つの方法で削除できます。

==== 右クリックメニューから削除
. btn:[クラウドストレージ] -> btn:[ブリーフケース]をクリックします。
. ファイルを右クリックして *削除* を選択します。
. ファイルは削除され、ゴミ箱フォルダーに移動します。

==== 削除ボタンで削除
. btn:[クラウドストレージ] -> btn:[ブリーフケース]をクリックします。
. ファイルを選択します。
. プレビューウィンドウの上にあるツールバーの btn:[削除] をクリックする。
. ファイルは削除され、ゴミ箱フォルダーに移動します。


=== ブリーフケースのカスタムフォルダー/サブフォルダーの移動
カスタムフォルダー/サブフォルダーを作成した場合、それらのフォルダーを他のフォルダーに移動することができます。

. btn:[クラウドストレージ] -> btn:[ブリーフケース]をクリックします。
. フォルダー／サブフォルダーを右クリックして、コンテキストメニューから *フォルダを移動* を選択します。
. 移動先のフォルダーを選択します。


=== ブリーフケースのカスタムフォルダー/サブフォルダーの名前変更
. btn:[クラウドストレージ] -> btn:[ブリーフケース]をクリックします。
. フォルダー/サブフォルダーを右クリックして、コンテキストメニューから *フォルダ名を変更* を選択します。
. テキストボックスに、フォルダーl/サブフォルダーlの新しい名前を入力します。
. kbd:[Enter]キーを押して保存します。

TIP: フォルダーの数が多い場合は、image:graphics/search.svg[magnifying glass icon, width=20]にフォルダー名を入力して検索することができます。

=== ブリーフケースからメールにファイルを添付する

IMPORTANT: このオプションは、ユーザのブリーフケース機能が有効になっている場合にのみ利用できます。

ブリーフケースにあるファイルは、電子メールに添付できます。

. メール作成画面で image:graphics/paperclip.svg[width=20px] をクリックすると、ファイル添付オプションが表示されます。
. **ブリーフケースからファイルを添付** をクリックすると、ファイルエクスプローラーが表示されます。
. フォルダーに移動し、添付するファイルを選択して、**添付**をクリックします。
選択したファイルが添付ファイルとして表示されます。

IMPORTANT: インラインイメージはブリーフケースからは追加できません。

=== メールからブリーフケースへファイルのアップロード
メールからのファイルは、直接ブリーフケースにアップロードすることができます。

. 添付ファイルのあるメールを選択します。
. メールのプレビューウィンドウで、添付ファイルにカーソルを置き、image:graphics/briefcase.svg[briefcase icon, width=20px]をクリックします。
. ファイルエクスプローラーで、フォルダーを選択し、btn:[保存]をクリックします。
. ファイルのアップロードに成功すると、 *添付ファイルがブリーフケースに追加されました。* というメッセージが表示されます。
