=== イベントの管理
==== イベントを予約する
. [カレンダー] のタブをクリックします。
. [新規イベント] のボタンをクリックします。
. *イベントを追加* にて、イベントの件名を入力します。
. イベントの開始と終了時間を選択するか、 *全日* を選択します。
.. 開始と終了時間に対して、イベントのタイムゾーンを個別に指定することが可能です。イベントのタイムゾーンを指定する場合、<<settings-otheroptions.adoc#_general_calendar_settings, カレンダーの設定>> で適切な機能を有効化します。
. 予定の場所を設定します。この情報は任意です。
. 自分自身のカレンダーでのみイベントを予定する場合、参加者を選択しない。
+
NOTE: 複数の参加者がある会議、などのイベントを作成する場合、参加者のメールアドレスを入力します。また、メールアドレスの入力以外に、 *参加者* をクリックし、リストから参加者を選択することも可能です。

. 追加情報、などの詳細を *備考* へ入力します。クリップアイコンをクリックしますと、 *備考* へ添付ファイルを追加することも可能です。
. *リマインダーを送信* にリマインドの通知を表示する期間を選択します。設定した時間内でイベント開始の通知が表示されます。
+
NOTE: イベント開始の通知を発生させたくない場合、 *チェックしない* を選択します。

. リマインダー通知を受信する方法を選択します、携帯/デスクトップアプリ内、またはメールでの通知が可能です。
. イベントが表示するステータスを指定します：予定なし、仮承認、予定あり、または外出中
. *カレンダー* にてイベントを追加するカレンダーを選択します。
. *保存* をクリックし、カレンダーへイベントを追加します。

==== イベントを編集する
. カレンダーに編集するイベントを確認します。
. イベントを右クリックし、 *編集* をメニューから選択します。
.. 代わりに、以下も可能：
** マウスをイベントの上に置いて、 *詳細* 、 *印刷* 、および *削除* が表示するオプションを確認します。 
** *詳細* をクリックし、 上にある image:graphics/pencil.svg[pencil icon, width=20] の編集アイコンをクリックします。
. <<_イベントを予約する>> の操作と同様な編集画面が表示します。
. 適切な情報を編集し、 *保存* をクリックします。

==== イベントを削除する
. カレンダーから削除するイベントを確認します。
. マウスをイベントの上に置いて、 *詳細* 、 *印刷* 、および *削除* が表示するオプションを確認します。
. *削除* をクリックします。
.. 代わりに、イベントを右クリックし、メニューから *削除* を選択します。
. UI の上に「予定が削除されました」通知が表示し、イベントの削除をお知らせます。

==== イベントをコピーする
. カレンダーにコピーするイベントを確認します。
. イベントを右クリックし、 *コピーする* をメニューから選択します。
. <<_イベントを予約する>> の操作と同様な編集画面が表示します。
. 適切な情報を編集し、 *保存* をクリックします。

==== イベントを転送する
繰り返しイベントやその中の特定のイベントを転送するためにカレンダーイベントを右クリックして開かれたメニュー内の *転送* アクションを利用できます。

. カレンダー内で転送するために予約にポイントします。
. コンテキストメニューを開くためにイベント上で右クリックし、 *転送* を選択します。
. もし、選択したイベントが <<イベント（予約/会議）の繰り返し, 繰り返しイベント>> ならば、 *このイベントのみ* または、 *すべてのイベント* を選択します。
. *宛先* フィールドに招待者を追加します。
. *備考* に追加情報を記載することができます。
. イベントを転送するために btn:[送信] ボタンをクリックしてください。

==== 新しい時間を提案する
イベントに新しい時間を提案することができます。
招待メールを受け取るとき、または後でカレンダーから、新しい時間を提案することができます。

招待メールから新しい時間を提案する::
招待メール内の出欠確認から *新しい時間を提案する* image:graphics/calendar-range.svg[width=20] をクリックします。
*新しい時間を提案する* 画面で希望する時間をセットし、 btn:[送信] ボタンをクリックします。

カレンダーから新しい時間を提案する::
. カレンダー内で新しい時間を提案したい予約をポイントします。
. コンテキストメニューを開くためにイベント上で右クリックし、 *新しい時間を提案する* を選択します。
. もし、選択したイベントが <<イベント（予約/会議）の繰り返し, 繰り返しイベント>> ならば、新しい時間を提案したい *このイベントのみ* または、 *すべてのイベント* を選択します。
. *新しい時間を提案する* 画面で希望する時間をセットし、 btn:[送信] ボタンをクリックします。
. 提案した時間が送信される際、トースター通知が表示されます。

==== イベント（予約/会議）の繰り返し
イベントを毎日、毎週、毎月、または毎年で繰り返しするように設定することが可能です。繰り返しのパターンもカスタマイズすることが可能、例えば3週間の金曜日、月の第3の金曜日、など。

以下は一般的なシナリオやイベントの繰り返し設定の事例となります。

_毎月の4日の朝11:00でペットを医者に定時的の健康診断を行いたいので、リマインダーを設定する希望です。次の医者予約は5月の4日です。_

開始日時:: 05/04/20XX 11:00 AM

終了日時:: 05/04/20XX 11:30 AM

繰り返し:: 毎月

_田中さんの誕生日は7月の20日です。その日に「誕生日おめでとう！」等のあいさつを忘れないため、リマインダーを設定したい。_

開始日時:: 07/20/20XX 07:00 PM. *全日* のチェックを追加します。

表示レベル:: 予定なし

繰り返し:: 毎年

_本日中に会社のチームに新しい開発についての会議がある。その後、会議を2週ごとの金曜日で予定したい。_

開始日時:: 07/20/20XX 07:00 PM

終了日時:: 07/20/20XX 07:30 AM

繰り返し:: カスタム -- *繰り返し間隔* 2 *週間* +
*日付* 金曜日（F）
*終了* 終了しない

他の繰り返しパターンを同様に設定することが可能です。

==== 繰り返しのイベントを編集する
. カレンダーに編集するイベントを確認します。
. マウスをイベントの上に置いて、 *詳細* 、 *印刷* 、および *削除* が表示するオプションを確認します。 
. *詳細* をクリックし、 上にある image:graphics/pencil.svg[pencil icon, width=20] の編集アイコンをクリックします。
. 「定時的なイベントを編集」の画面にて、選択したイベントのみのを編集、または全部繰り返しするイベントの編集を選択します。
. <<_イベントを予約する>> の操作と同様な編集画面が表示します。
. 適切な情報を編集し、 *保存* をクリックします。

==== 繰り返しのイベントを削除する
. カレンダーから削除するイベントを確認します。
. マウスをイベントの上に置いて、 *詳細* 、 *印刷* 、および *削除* が表示するオプションを確認します。
. *削除* をクリックします。
. 「定時的なイベントを削除」の画面にて、選択したイベントのみのを削除、または全部繰り返しするイベントの削除を選択します。
. UI の上に「予定が削除されました」通知が表示し、イベントの削除をお知らせます。

==== イベントの招待へ返事する

イベントの招待が *Inbox* へ image:graphics/calendar-o.svg[calendar icon, width=20] のアイコンで受信します。
参加者であれば、返答可能なレスポンスは3つとなります。
招待の RSVP 部分にて、返信メールを送信するオプションがあります。

*受け入れる* image:graphics/check-circle.svg[width=20]: {product-name} を選択すると、イベントがカレンダーへ追加します。イベントが開始する前にリマインダーの通知が行います。

*仮承認* image:graphics/question-circle.svg[width=20]: {product-name} を選択すると、イベントがカレンダーへ追加します。イベントが開始する前にリマインダーの通知が行います。ただし、イベントを後で受け入れるか拒否へ選択しを変更できます。

*拒否* image:graphics/close-circle.svg[width=20]: {product-name} を選択すると、イベントが削除し、カレンダーへ追加しません。

*新しい時間を提案する* image:graphics/calendar-range.svg[width=20]: {product-short} を選択すると、編集イベントの <<新しい時間を提案する>> ダイアログが開かれます。

NOTE: イベントオーガナイザーは、新しい時間の提案を承認、あるいは拒否するオプションを持っています。

{product-short} は、左のバーにまだ返信していない招待をマークします。
招待に対し、カレンダー、もしくはメールセクション内で返信するかもしれません。
一度、返信したならば、 {product-short} は、招待メールを削除します。

{product-name} はまだ返答していない招待をカレンダーで表示し、左側で黄色の線で示します。
カレンダー上、またはメールにて、招待へ返答することが可能です。
招待に返答しましたら、{product-name} が招待メールを自動的に削除します。

==== リマインド通知を停止、または延期する

*リマインド* ダイアログボックスは、予約、またはミーティング時間になったとき、あるいは、タスクが完了する際にポップアップします。

リマインド通知は、 *閉じる* をクリックすることによって、停止できます。また *スヌーズ* をクリックすることによって、1分間、ポーズすることができます。

リマインド通知ボックスは、複数のイベントをリストするかもしれません。
_すべて_ のリマインド通知を停止する場合、*すべて閉じる* をクリックします。

同様に *すべてスヌーズ* は、 _すべて_ のリマインド通知を1分間、ポーズします。
