=== イベントの管理
==== イベントを予約する
. btn:[カレンダー] タブを選択します。
. btn:[新しい予定] ボタンをクリックします。
. *予定を追加* フィールドに、イベントの件名を入力します。
. イベントの開始と終了時間を選択するか、 *全日* を選択します。
.. 開始と終了時間に対して、イベントのタイムゾーンを個別に指定することが可能です。イベントのタイムゾーンを指定する場合、<<settings-calendars-reminders.adoc#_カレンダー設定, カレンダーの設定>> で適切な機能を有効化します。
. 予定の場所を設定します。この情報は任意です。
. 自分自身のカレンダーでのみイベントを予定する場合には参加者を選択する必要はありません。
+
NOTE: 複数の参加者がある会議などのイベントを作成する場合は、参加者のメールアドレスを入力します。また、メールアドレスを直接入力する以外に、 *参加者* をクリックし、リストから参加者を選択することも可能です。

. 追加情報などの詳細を *備考* へ入力します。クリップアイコンをクリックすると、 *備考* へ添付ファイルを追加することもできます。
. *リマインダー* にリマインドの通知を表示する期間を選択します。設定した時間になるとイベント開始の通知が表示されます。
+
NOTE: イベント開始の通知を発生させたくない場合、 *チェックしない* を選択します。

. リマインダー通知を受信する方法を選択します。チェックした場合は携帯/デスクトップアプリ内、チェックしない場合はメールでの通知となります。
. *表示ラベル* で自分のカレンダーや共有先のカレンダー上で表示される、イベントのステータスを指定します。予定なし、仮承認、予定あり、または外出中を指定できます。
. イベントの保存先カレンダーが選択されている場合や、デフォルトのカレンダー以外を作成していない場合は、*カレンダー* フィールドはそのままにしておきます。
. btn:[保存] をクリックし、カレンダーへイベントを追加します。

==== イベントを編集する
. カレンダーから編集するイベントを確認します。
. イベントを右クリックし、 *編集* をメニューから選択します。
** 代わりに、以下の操作も可能です：マウスカーソルをイベントの上に合わせると、 *詳細* 、 image:graphics/pencil.svg[pencil icon, width=20] (編集)、image:graphics/print.svg[print icon, width=20] (印刷)、 image:graphics/trash.svg[trash icon, width=20] (削除) オプションが表示されます。
... image:graphics/pencil.svg[pencil icon, width=20] をクリックします。
... *詳細* をクリックし、 上にある image:graphics/pencil.svg[pencil icon, width=20] をクリックします。
. <<_イベントを予約する>> の操作と同様な編集画面が表示されます。
. 適切な情報を編集し、 btn:[保存] をクリックします。

==== イベントを削除する
. カレンダーから削除するイベントを確認します。
. マウスカーソルをイベントの上に合わせると、 *詳細* 、  image:graphics/pencil.svg[pencil icon, width=20] (編集)、image:graphics/print.svg[print icon, width=20] (印刷)、 image:graphics/trash.svg[trash icon, width=20] (削除) オプションが表示されます。
. image:graphics/trash.svg[trash icon, width=20] をクリックします。
.. 代わりに、イベントを右クリックし、メニューから *削除* を選択します。
. イベントが削除され、「予定が削除されました」の通知が表示されます。

==== イベントをコピーする
. カレンダーからコピーするイベントを確認します。
. イベントを右クリックし、 *コピーする* をメニューから選択します。
. <<_イベントを予約する>> の操作と同様な編集画面が表示されます。
. 適切な情報を編集し、 btn:[保存] をクリックします。

==== イベントを転送する
繰り返しイベントやその中の特定のイベントを転送するために、カレンダーイベントを右クリックして開かれたメニュー内の *転送* アクションを利用できます。

. カレンダーから転送する予定を探します。
. イベント上で右クリックし、 *転送* を選択します。
. もし、選択したイベントが <<_イベント予約会議の繰り返し, 繰り返しイベント>> ならば、 *この予定のみ* または、 *すべての予定* を選択します。
. *宛先* フィールドに招待者を追加します。
. *備考* に追加情報を記載することができます。
. イベントを転送するために btn:[送信] をクリックします。

==== 新しい時間を提案する
イベントに新しい時間を提案することができます。
招待メールを受け取ったとき、または後でカレンダーから、新しい時間を提案することができます。

招待メールから新しい時間を提案する::
招待メール内の出欠確認から *新しい時間を提案* image:graphics/calendar-range.svg[width=20] をクリックします。
*新しい時間を提案* 画面で希望する時間をセットし、 btn:[送信] をクリックします。

カレンダーから新しい時間を提案する::
. カレンダーから新しい時間を提案したい予約を確認します。
. イベント上で右クリックし、 *新しい時間を提案する* を選択します。
. もし、選択したイベントが <<_イベント予約会議の繰り返し, 繰り返しイベント>> ならば、新しい時間を提案したい *この予定のみ* または、 *すべての予定* を選択します。
. *新しい時間を提案* 画面で希望する時間をセットし、 btn:[送信] をクリックします。
. 提案した時間が送信される際、「新しい時間が提案されました。」の通知が表示されます。

==== イベント（予約/会議）の繰り返し

NOTE: 終了日や発生回数の制限がない反復イベントを設定する場合、管理者により設定された繰り返し期間・回数の制限が適用される場合があります。これは、日次、週次、月次、年次の定期イベントに適用されます。

イベントを毎日、毎週、毎月、または毎年で繰り返しするように設定することが可能です。繰り返しのパターンもカスタマイズすることが可能で、例えば毎月の第3金曜日、などが可能です。

以下は一般的なシナリオやイベントの繰り返し設定の事例となります。

_毎月4日の朝11:00にペットを健康診断に連れて行きたいので、リマインダーを設定します。次の予約は5月4日です。_

開始日時:: 05/04/20XX 11:00 AM

終了日時:: 05/04/20XX 11:30 AM

繰り返し:: 毎月

_田中さんの誕生日は7月20日です。その日に「誕生日おめでとう！」等のあいさつを忘れないため、リマインダーを設定します。_

開始日時:: 07/20/20XX 07:00 PM. *全日* のチェックを追加します。

表示ラベル:: 予定なし

繰り返し:: 毎年

_本日、チーム会議があります。今後、2週間ごと（隔週）の金曜日に開催します。_

開始日時:: 07/20/20XX 07:00 PM

終了日時:: 07/20/20XX 07:30 AM

繰り返し:: カスタム -- *繰り返し間隔* 2 *週間* +
*日付* 金曜日（F）
*終了* 終了しない

他の繰り返しパターンを同様に設定することが可能です。

==== 繰り返しのイベントを編集する
. カレンダーから編集するイベントを確認します。
. マウスカーソルをイベントの上に合わせると、 *詳細* 、 image:graphics/pencil.svg[pencil icon, width=20] (編集)、image:graphics/print.svg[print icon, width=20] (印刷)、 image:graphics/trash.svg[trash icon, width=20] (削除) オプションが表示されます。
. image:graphics/pencil.svg[pencil icon, width=20] アイコンをクリックすることもできます。
** 代わりに、*詳細* をクリックし、 上部のメニューバーから image:graphics/pencil.svg[pencil icon, width=20] の編集アイコンをクリックします。
. 「繰り返しイベントを編集」ダイアログにて、 *この予定のみ* または、 *すべての予定* を選択します。
. <<_イベントを予約する>> の操作と同様な編集画面が表示されます。
. 適切な情報を編集し、 btn:[保存] をクリックします。

==== 繰り返しのイベントを削除する
. カレンダーから削除するイベントを確認します。
. マウスカーソルをイベントの上に合わせると、 *詳細* 、image:graphics/pencil.svg[pencil icon, width=20] (編集)、image:graphics/print.svg[print icon, width=20] (印刷)、 image:graphics/trash.svg[trash icon, width=20] (削除) オプションが表示されます。
. image:graphics/trash.svg[trash icon, width=20] をクリックすることもできます。
** 代わりに、*詳細* をクリックし、上部のメニューバーからimage:graphics/trash.svg[trash icon, width=20] の削除アイコンをクリックします。
. 「繰り返しの予定を削除」ダイアログにて、 *この予定のみ* または、 *すべての予定* を選択します。
. 予定が削除される際、「予定が削除されました」の通知が表示されます。

==== イベントの招待に返事をする

イベントの招待状は、image:graphics/calendar-o.svg[calendar icon, width=20] アイコンが付いたメールとして *受信箱* に表示されます。
自分がイベントに招待されている場合、イベントに対してとり得るアクションは3種類あります。
招待状の出欠確認セクションでは、応答メールを作成者に送信するか、新しい時間を提案するかのオプションがあります。
出欠確認セクションのアクション（受け入れる、仮承諾、拒否）のどれかをクリックすると、チェックボックスとテキストエリアが表示されます。
チェックボックスにチェックを入れ、返事を入力して、btn:[保存]をクリックすると、作成者に返事が送信されます。

*受け入れる* image:graphics/check-circle.svg[width=20]: {product-short}は、カレンダーにイベントを保存します。
そのイベントが始まる前には、通知で知らせます。

*仮承認* image:graphics/question-circle.svg[width=20]:  {product-short}は、カレンダーにイベントを保存します。
そのイベントが始まる前には、通知で知らせます。
しかし、いつでもそのイベントを見直すことができ、「受け入れる」または「拒否」に変更することができます。

*拒否* image:graphics/close-circle.svg[width=20]: {product-short}はイベントを削除し、そのイベントはあなたのカレンダーには載りません。


*新しい時間を提案* image:graphics/calendar-range.svg[width=20]: {product-short} は、イベントの編集画面を表示して、そのイベントについて <<_新しい時間を提案する, 新しい時間を提案>> を行います。


NOTE: イベント主催者は、提案された時間を受け入れるか拒否するかを選択できます。

{product-short}では、まだ返事をしていない招待について、カレンダーにイベントを表示するとき、イベント枠の左端に黄色い線を付けて示します。
招待状への返信は、btn:[カレンダー]またはbtn:[メール]で行うことができます。
返事をすると、{product-short}は招待メールを削除します。

==== リマインド通知を停止、または延期する

*予定のリマインダー* ダイアログボックスは、予約、またはミーティング時間になったとき、あるいは、タスクが完了する際にポップアップします。

リマインド通知は、 *閉じる* をクリックすることによって停止できます。また、 *スヌーズ* をクリックすることによって1分後に再通知させることができます。

リマインダーダイアログボックスには、複数のイベントが表示されることがあります。
_すべて_ のリマインド通知を停止する場合、*すべて閉じる* をクリックします。

同様に、*すべてスヌーズ* は、 _すべて_ のリマインダーを1分後に再通知させます。
