== タスク
=== 新しいタスクリストを作成する

. btn:[カレンダー] タブを選択します。
. image:graphics/ellipsis-h.svg[3 dots menu icon, width=20] のアイコンをクリックします。
. *リストを作成...* をクリックします。
. 「タスクリストを作成」の画面にリスト名を入力し、btn:[リストを作成] をクリックします。
. 新しいタスクリストが右側に追加されます。

=== 新しいタスクを作成する
さまざまなリストをひとつにまとめたり、リマインダーを表示したり、タスクの進捗状況を確認したりすることができます。

. btn:[カレンダー] タブを選択します。
. image:graphics/ellipsis-h.svg[3 dots menu icon, width=20] のアイコンをクリックし、 *新しいタスク* を選択します。
+
NOTE: <<_完了ビュー>> の場合、このオプションは選択できません。

. タスクの期限を *期限* フィールドに設定します。
. ドロップダウンメニューからタスクの優先度を選択します。 *低* 、 *標準* 、 *高* の優先度を選択できます。
. タスクを適切な <<_新しいタスクリストを作成する, リスト>> に関連づけます。
. タスクに関連する追加情報は、*備考* セクションに入力します。

あるいは、

. <<calendar-overview.adoc#_右側のタスクリスト, 右側のタスクリスト>> で、タスクを追加するリストの上にマウスカーソルを合わせ、 *タスクを追加* ボックスをクリックします。
. タスク名を入力します。
. kbd:[Enter]を押して、タスクを保存します。
. タスクの締め切りや優先度を指定するためには、<<_タスクを編集する, タスクを編集します>>。

=== タスクを編集する
. 作成したタスクをクリックすると、 *編集* と *削除* のオプションが表示されます。
. *編集* をクリックします。

<<_新しいタスクを作成する>> 時の手順と同じインターフェースとオプションが表示されますので、必要な編集を行います。

=== タスクを削除する
. 作成したタスクをクリックすると、 *編集* と *削除* のオプションが表示されます。
. *削除* をクリックします。
. タスクが削除し、「タスク削除しました」の通知が画面に上に表示されます。

=== タスクリストのビュー順番
タスクリストを <<_リストビュー, アルファベット順リスト>>、<<_優先度ビュー,優先度順>>、 <<_期限ビュー,締め切り順>>、または <<_完了ビュー,終了したタスク>> で表示することが可能です。

==== リストビュー
すべてのタスクと関連しているリストを表示します。リストはアルファベット順で表示されます。リストに関連しているタスクは作成順番で表示され、最新のタスクが先頭に表示されます。

==== 優先度ビュー
タスクは優先度の順番で表示されます。優先度の *高い* 順で表示されます。

==== 期限ビュー
タスクの締め切りの順番で表示されます。締め切りが近い順で表示されますが、例外として締め切りをすぎたタスクは最初に表示されます。

==== 完了ビュー
完了したタスクのみが表示されます。
