== タスク
=== 新しいタスクリストを作成する
. image:graphics/ellipsis-h.svg[3 dots menu icon, width=20] のアイコンをクリックします。
. *リストを作成t...* をクリックします。
. 「タスクリストを作成」の画面にリスト名を入力し、[リストを作成] をクリックします。
. 新しいタスクリストが右側に追加します。

=== 新しいタスクを作成する
複数のリストの合体、リマインダーを受信、およびタスクの進歩状況を確認することが可能です。

. [カレンダー] のタブをアクセスします。
. image:graphics/ellipsis-h.svg[3 dots menu icon, width=20] のアイコンをクリックし、 *新しいタスク* を選択します。
+
[NOTE]
<<完了ビュー>> の場合、このオプションが非表示します。

. *期限* にて、タスクの締め切りを指定します。
. ドロップダウンメニューからタスクの優先度を選択します。 *低* 、 *標準* 、および *高* の優先度を選択てきます。
. タスクを適切な <<新しいタスクリストを作成する, リスト>> に関連します。
. *備考* にて、タスクに関するその他の詳細を記入します。

代わりに、

. <<calendar-overview.adoc#_tasks_pane, 右側のタスクリスト>> にて、タスクを追加するリストの上にマウスを置き、[タスクを追加] のボックスをクリックします。
. タスク名を入力します。
. キーボードのEnterキーでタスクが保存します。
. タスクの締め切りや優先度を指定するため、<<タスクを編集する, タスクを編集します>>。

=== タスクを編集する
. 作成したタスクをクリックしますと、 *編集* と *削除* のオプションが表示します。
. *編集* をクリックします。

<<新しいタスクを作成する>> の手順にある同一のインターフェースとオプションが表示しますので、必要な編集を行います。

=== タスクを削除する
. 作成したタスクをクリックしますと、 *編集* と *削除* のオプションが表示します。
. *削除* をクリックします。
. タスクが削除し、「タスク削除しました」の通知が画面に上に表示します。

=== タスクリストのビュー順番
タスクリストを <<リストビュー, 一般的なリスト順番>>、<<優先度ビュー,優先の順番>>、 <<期限ビュー,締め切りの順番>>、または <<完了ビュー,終了したタスク>> として表示することが可能です。

==== リストビュー
すべてのタスクと関連しているリストを表します。リストはアルファベット順で表示します。リストに関連しているタスクは作成順番で表示されます：最新に作成したタスクはリストの上に表示します。

==== 優先度ビュー
タスクは優先度の順位で表示します。*高* が上からの順番で表示します。

==== 期限ビュー
タスクの締め切りの順位で標示します。締め切りが近い順番で上から表示しますが、例外として締め切りを継ぎたタスクが最初に表示します。

==== 完了ビュー
完了したタスクのみが表示します。
