=== メールの検索ボックス
<<mail-overview.adoc#_メールのプレビューウインドウ>> の上にある検索ボックスにメールメッセージを検索するキーワードを入力できます。キーワード検索以外に、特定のフォルダでの検索や全フォルダの検索が可能です。

検索する場合、検索するキーワードを検索ボックスへ入力し、kbd:[Enter] を押します。

=== 詳細な検索
検索ボックスの右横にある image:graphics/chevron-down.svg[down icon, width=20] をクリックすると、検索条件をより細かく指定することが可能です。

. **検索場所** にて、検索するフォルダを選択します。
. **差出人** フィールドにメールアドレスを入力すると、その *アドレスから送信された* すべてのメールが検索対象となります。
. 同様に、**宛先**フィールドにメールアドレスを入力すると、その *アドレスに送られた* すべてのメールが検索対象となります。
. **件名** のチェックボックスにチェックを入れると、メールの件名にあるキーワードで検索されます。
. **メッセージ本文** のチェックボックスにチェックを入れると、メールの本文にあるキーワードで検索されます。
検索した文字列を引用符で囲むと、フレーズとして検索されます。
. **日付** は検索する期間を指定することができます。
. 探しているメールに画像や添付ファイルがある場合は、**添付ファイル** のチェックボックスにチェックを入れます。

NOTE: 上記の検索条件はいずれも必須ではありません。
しかし、条件を追加することで、検索時間を短縮し、さらに検索結果を絞り込むことができます。

=== 検索結果

* *メッセージ* をクリックすると検索結果のメッセージ一覧が表示されます (デフォルト表示)。
* *写真* をクリックすると検索結果に含まれる画像ファイルが表示されます。例えば PNF、JPG、GIF、BPM などの拡張子がついたファイルが対象です。
* *文書* をクリックすると検索結果に含まれる画像以外のファイルが表示されます。

==== 保存済み検索

*検索を保存* すると、後で再び使用する検索クエリを保存できます。

. <<_メールの検索ボックス>> 又は <<_詳細な検索>> で検索クエリを作成します。
. <<_検索結果>> 画面の上部の *検索を保存* をクリックします。
. 検索の名前を入力します。
.  btn:[保存] をクリックします。

保存された検索は、<<mail-overview.adoc#_左サイドバー, 左サイドバー>> の *保存済み検索* に保存されます。

保存した検索クエリを使用するには、*保存済み検索* 内の当該アイテムをクリックします。すると、<<mail-overview.adoc#_リストペイン>> に検索結果が表示されます。
