=== メールを書く
==== 送信を取り消す
*送信を取り消す* の機能では、送信したメールを巻き戻すことが可能です。
この機能を有効化しますと、メールを送信した後に *取り消す* ボタンの通知が表示ます。
この通知が数秒間で表示します。
通知が消えますと、送信の取り消しができなくなります。

この通知が画面上で表示する間、メールが *下書き* のフォルダーに残します。
*取り消し* をクリックしますと、送信がキャンセルされた通知が表示し、メールが *下書き* のフォルダーで残ります。

. image:graphics/cog.svg[cog icon, width=20] -> *設定* をアクセスします。
. *メールを書く* にて、*送信を取り消す* に *有効にする* のチェックボックスにチェックを追加することで、この機能を有効化します。
. 画面の下に *保存* をクリックします。

==== 閲覧確認を要求
メールを送信する際に、受信先からメールの閲覧確認の通知を常に要求することが可能です。

. image:graphics/cog.svg[cog icon, width=20] -> *設定* をアクセスします。
. *メールを書く* にて、*閲覧確認を要求* に *常時* のチェックボックスにチェックを追加することで、この機能を有効化します。
. 画面の下に *保存* をクリックします。

ご注意：常に要求すること以外に、<<mail-compose.adoc#_request_read_receipts>> にて、メールを作成する際に任意で閲覧確認の要求をすることが可能ですので、参照してください。

==== コピーを送信済みフォルダーに保存する
送信したメールのコピーを *送信済み* のフォルダーへ保存しないように設定することが可能です。

. image:graphics/cog.svg[cog icon, width=20] -> *設定* をアクセスします。
. *メールを書く* にて、*コピーを送信済みフォルダーに保存する* に *有効にする* のチェックボックスにチェックを外すことで、送信済みのフォルダーへメールの保存を行わないようにします。
. 画面の下に *保存* をクリックします。

==== 代行者
{product-name} で別のユーザーをメールアカウントの管理を代行に任せることが可能です。代行者は代理にメールの閲覧、送信、および削除が可能です。
代行者が代理に送信したメールは元アドレスの所有者として送信します。

. image:graphics/cog.svg[cog icon, width=20] -> *設定* をアクセスします。
. *メールを書く* にて、*代行者* で *代行者を追加...* をクリックします。
. 代行者の名前やメールアドレスを入力します。
オートコンプリートの機能により、推奨するアドレスが表示ます。適切なアドレスを選択してください。
. 代行者は *形式を指定して送信* か *代理送信* に利用できるか、選択します。Choose whether delegates can *Send As* or *Send on behalf of*
+
形式を指定して送信:: 代行者が完全にアカウントの所有者に化けて、メールを送信します。
メールの受信先では、送信者がアカウントの所有者から送信されたように見えます。
代理送信:: 代行者が代理にメールを送信します。メールの受信先では、送信者に代行者のメールアドレスが所有者の代理に送信されたことを確認できます。

===== 代行送信設定
代行者が形式を指定してメールを送信、または代理送信した場合、送信したメールが保存する方法を管理することができます。

送信したメッセージを自分の送信済みフォルダに保存:: 代行者が送信したメールのコピーが所有者の送信済みフォルダーへ保存します。
送信したメッセージを代行者の送信済みフォルダに保存:: 代行者が送信したメールのコピーが代行者の送信済みフォルダーへ保存します。
送信したメッセージを自分の送信済みフォルダと代行者の送信済みフォルダに保存:: 代行者が送信したメールのコピーが所有者の送信済みフォルダー、および代行者の送信済みフォルダーへ保存します。
送信したメッセージを保存しない:: {product-name} が代行者で送信したメールのコピーを保存しない。
