=== アカウント設定

==== アカウントの追加
Modern Web Appでは、他のメールアドレスで受信したメールを管理することができます。
Modern Web App を通じて、これらのメールアドレスを使ってメールを送受信することができます。

. image:graphics/cog.svg[cog icon, width=20] -> *設定* を選択します。
. *アカウント* をクリックし、image:graphics/plus.svg[width=20] *アカウントを追加* を選択します。
. *メールアドレス* の欄にメールアドレスを入力します。
. *パスワード* 欄に、このメールアドレスのパスワードを入力します。
+
--
TIP: お使いのメールプロバイダーがアプリのパスワードの生成を義務付けている場合は、そのパスワードを生成する必要があります。
生成されたら、 *パスワード* フィールドにアプリのパスワードを使用します。
--
+
. Modern Web Appで設定するアカウントタイプを、 *POP3* または *IMAP4* から選択します。
. このメールアドレスに関連するユーザー名を入力します。
. *メールサーバー* フィールドにメールサーバー名を入力します。

この情報については、お使いのメールプロバイダーに確認してください。

ここでは、代表的なサービスプロバイダーの詳細をご紹介します。
[cols="40,40,40,40,40,40",options="header"]
|=======================================================================
|メールプロバイダ | IMAPホスト/ポート | POPホスト/ポート | SSL | アプリパスワード | "安全性の低いアプリ"設定の有効化

|Gmail
|imap.gmail.com / 993
|pop.gmail.com / 995
|必要
|不要
|必要
|=======================================================================

==== {product-short} アカウントの名前を変更する
メールを送信する際に表示する名前を指定することが可能です。

. image:graphics/cog.svg[cog icon, width=20] -> *設定* を選択します。
. *アカウント* をクリックし、編集するアカウントを選択します。
. *お名前* にて、メールを送信した際に、宛先側で表示する名前を入力します。
. 画面の下の *保存* をクリックします。

==== {product-short} のメールボックス名を変更する
複数のメールアカウントを {product-short} に設定している場合、各アカウントを個別に利用できるようにしh多い場合があります。

. image:graphics/cog.svg[cog icon, width=20] -> *設定* を選択します。
. *アカウント* をクリックし、編集するアカウントを選択します。
. *説明* にて、アカウントを示せる名前を入力します。
. 画面の下の *保存* をクリックします。

==== ペルソナの追加
ペルソナは、さまざまな種類のメールを管理するために、個別のメールアイデンティティを作成するのに役立ちます。
例えば、ビジネスメール用のペルソナと、個人用のペルソナを作成することができます。
ペルソナを使用すると、そのペルソナを使用して送信されるメールに、異なる *From* アドレスや *Reply-To* アドレスを指定することができます。
すべての送信メールには、使用しているペルソナのメールアドレスが表示されます。

. image:graphics/cog.svg[cog icon, width=20] -> *設定* を選択します。
. 左ペインの *アカウント* をクリックし、image:graphics/plus.svg[width=20] *ペルソナを追加* を選択します。
. ペルソナを識別するために、 *ペルソナ名* に名前を入力します。
. *このアカウントから送信* からアカウントを選択します。
. 受信者が送信者の名前として認識できる名前を入力します。
+
--
TIP: このボックスが空の場合、ペルソナは送信アカウントの差出人名を使用します。
--
+
. 返信を別のメールアドレスで受信するには、「返信を別のメールアドレスに送信する」の *有効* をチェックしてください。
.. _返信先のアドレス_ を入力してください。
.. _返信先名_ を入力してください。
. *ペルソナを追加* をクリックして、ペルソナを作成します。

==== 二要素認証
アカウントに二要素認証（2FA）を有効化や無効化するオプションが提供している可能性があります。

===== 2FA を有効化する
管理者が二要素認証を有効化しているが、強制的に運用していない場合、二要素認証を任意で設定することが可能です。
設定しない場合、アプリケーションの動作が変わりません。

. image:graphics/cog.svg[cog icon, width=20] -> *設定* を選択します。
. *アカウント* をクリックし、2FAを有効化するアカウントを選択します。
. btn:[2要素認証をセットアップ] ボタンをクリックします。
. アカウントのパスワードを入力します。
. ご利用中の携帯端末に認証用のアプリをインストールします。
https://wiki.zimbra.com/wiki/TOTPApps[対応するアプリケーションのリスト] を参照してください。
. アプリのインストールが完了しましたら、携帯端末で設定します。
. {product-short} の画面にて、 *次へ* をクリックし、アカウントを認証用のアプリへ追加するプロセスを開始します。
. 認証用のアプリにて、QRコードをスキャンするか、{product-short} 画面で発行されたコードを入力します。
. *次へ* をクリックします。
. 認証用のアプリで発行した一時コードを入力し、 *認証* をクリックすることで、二要素認証の設定を完了します。

===== ログイン画面
設定完了後、{product-short} へログインする際に、一時的な認証コードも要求します。
認証用のアプリで発行した一時コードを入力し、 *認証* をクリックします。
ご利用中のアカウントに二要素認証が有効の状態となっています。

===== 信頼するデバイスを追加する
2FAを設定後、{product-short} は毎ログインで認証用のアプリから新しい認証コードを入力する必要となります。
ただし、特定の端末を信頼するデバイスとして設定することで、その端末からアクセスする際に認証コードの入力が必要なくなります。

. {product-short} にアクセスします。
. ユーザー名とパスワードでログインします。
. 認証コードの入力画面にて、 *このデバイスを信頼する* にチェックを入力します。
. 認証用のアプリで発行した一時コードを入力します。
. *認証* をクリックし、ログインします。

次回以降、この端末からログインする際には、認証コードを入力する必要はありません。

===== 信頼するデバイスを削除する
デバイスを信頼するデバイスのリストから外す場合、その端末からログインする際に、{product-short} が認証コードを改めて要求するように戻ります。
信頼するデバイスのリストからデバイスを削除する場合、まずはそのデバイスでログインします。

. image:graphics/cog.svg[cog icon, width=20] -> *設定* を選択します。
. *アカウント* をクリックし、編集するアカウントを選択します。
. *二要素認* へスクロールします。
. *このデバイスを信頼しないでください* をクリックします。

TIP: 信頼するデバイスのリストから、現在にログイン中のデバイス以外、他のデバイスをすべて削除する場合、*他のすべてのデバイスを無効にする* をクリックします。

{product-short} が直ちに信頼するデバイスリストから該当のデバイスを外します。

===== ワンタイムコードについて

認証用のアプリをアクセスできない場合、ワンタイムコードで二要素認を完了することが可能です。
ただし、これらのコードは1回限りご利用いただけます。
{product-short} は新しいコードを発行するオプションはあります。
二要素認証の設定後、緊急用としてこれらのコードをコピーし、安全な場所へ保管することを推奨します。

IMPORTANT: ワンタイムコードや認証用のアプリにアクセスできない場合、{product-short} へログインできません。

===== ワンタイムコードを発行する
. image:graphics/cog.svg[cog icon, width=20] -> *設定* を選択します。
. *アカウント* をクリックし、編集するアカウントを選択します。
. *二要素認証* へスクロールします。
. *10個の未使用コード* をクリックします。
. *クリップボードにコピー* をクリックするとコードをすべてコピーしますので、テキストファイルへ張り付けて、安全な場所に保存してください。

NOTE: *クリップボードにコピー* をクリックした後、 *コピーしました* に変更します。 *コピーしました* を改めてクリックすることで、再びコピーできます。

==== アプリの専用パスコードを作成する
ほとんどのデスクトップアプリでは二要素認証を行える一時コードの認証方法がありませんので、メーラソフトを設定する場合、アカウントの本当のパスワードではなく、{product-short} が専用のアプリパスコードを発行し、二要素認証を回避します。

. image:graphics/cog.svg[cog icon, width=20] -> *設定* を選択します。
. *アカウント* をクリックし、編集するアカウントを選択します。
. *二要素認証* へスクロールします。
. *パスコードを追加* をクリックします。
. 作成するアプリのパスコードを特定できる名前を入力し、 *次へ* をクリックします。
. コードをコピーし、テキストファイルへ張り付けて、安全な場所に保存してください。
メーラソフトウェアを設定する際に、このコードがアカウントのパスワードとして入力する必要があります。
. {product-short} のメールアドレスをメーラソフトウェアに設定する際、アカウントのパスワード入力する際に、このパスコードを利用します。

===== アプリの専用パスコードを削除する

. image:graphics/cog.svg[cog icon, width=20] -> *設定* を選択します。
. *アカウント* をクリックし、編集するアカウントを選択します。
. *二要素認証* へスクロールします。
. 削除するパスコードの上にマウスを置きます。
. image:graphics/close.svg[close icon, width=20] のアイコンをクリックし、パスコードを削除します。

===== 2FA を無効化にする

. image:graphics/cog.svg[cog icon, width=20] -> *設定* を選択します。
. *アカウント* をクリックし、編集するアカウントを選択します。
. *二要素認証* へスクロールします。
. *二要素認証を削除する* のボタンをクリックします。

上記の操作を完了後、再び追加の認証コードなしでログインが可能となります。

IMPORTANT: ご利用環境の管理者が 2FA の無効化オプションを提供している場合のみ、無効化することが可能です。

==== 返信先アドレスを設定する
この機能でメールの返信を別のメールアドレスへ受信するように設定いただけます。

. image:graphics/cog.svg[cog icon, width=20] -> *設定* を選択します。
. *アカウント* をクリックし、編集するアカウントを選択します。
. *返信先アドレス* へスクロールします。
. *送信したメールに対する返信を別のアドレスで受信します。* のチェックボックスにチェックを入力します。
. 送信したメールの返信先メールアドレスを入力します。
. 入力したメールアドレスに関連する名前を入力します。
. 画面の下の *保存* をクリックします。

==== 別の場所でメールをアクセスする
{product-short} に転送先のアドレスを設定することが可能です。{product-short} は指定した転送先アドレスへ、すべてのメールを転送します。

. image:graphics/cog.svg[cog icon, width=20] -> *設定* を選択します。
. *アカウント* をクリックし、編集するアカウントを選択します。
. *転送設定* へスクロールします。
. *指定したアドレスにメールを転送する* のチェックボックスにチェックを入力します。
. 転送先のメールアドレスを入力し、 *追加* のボタンをクリックします。
. メールを転送した後、{product-short} にもコピーを保管する場合、 *メッセージのコピーを保存する* のチェックボックスにチェックを入力します。

. 画面の下の *保存* をクリックします。

ifdef::Desktop_app[]
==== PSTファイルをインポートする
NOTE: この機能はWindows用の{product-short}デスクトップアプリでのみ提供しています。

メールアカウントをOutlookへ追加する場合、{product-short} がメールメッセージ、カレンダー情報、連絡先、およびタスクのローカルコピーを保存します。
多少のアカウントは Outlook データファイル (`.pst` ファイル）に情報を保存します。

これらの `PST` は {product-short} のデスクトップアプリに <<mail-localstorage.adoc#_local_storage, ローカルストレージ>> のフォルダーへインポートすることが可能です。
以下の手順では、該当の `PST` ファイルは既にコンピューター上にコピーしていることを前提しています。
メール、連絡先、およびカレンダーを `PST` ファイルとしてエクスポートやバックアップする場合、https://support.office.com/en-us/article/back-up-your-email-e5845b0b-1aeb-424f-924c-aa1c33b18833[Back up your email] を参照してください。

. image:graphics/cog.svg[cog icon, width=20] -> *設定* を選択します。
. *アカウント* をクリックし、編集するアカウントを選択します。
. *Import from Outlook (.pst file)* までスクロールします。
. *Choose .pst file* をクリックします。
. インポートする `PST` を選択します。
. *Import* をクリックします。

NOTE: {product-short}が`PST`をインポートしているあいだ、ローカルフォルダにアクセスできません。
*メール* は引き続き使用できますが、*カレンダー* と *連絡先* は使用できません。インポートが完了すると{product-short}が通知します。
endif::Desktop_app[]

==== データをエクスポートする
すべてのメール、連絡先、およびカレンダーを `.tgz` ファイルとしてエクスポートすることが可能です。
特定のフォルダー、メールメッセージ、連絡先、またはカレンダーをエクスポートする場合、それらのアイテムを右クリックし、メニューから *エクスポート* を選択します。

. image:graphics/cog.svg[cog icon, width=20] -> *設定* を選択します。
. *アカウント* をクリックし、編集するアカウントを選択します。
. 画面をスクロールし、btn:[エクスポート] ボタンをクリックします。

==== データをインポートする
`.tgz` ファイルからすべてのメール、連絡先、およびカレンダーをインポートすることが可能です。

. image:graphics/cog.svg[cog icon, width=20] -> *設定* を選択します。
. *アカウント* をクリックし、編集するアカウントを選択します。
. *インポート* へスクロールし、btn:[インポート] のボタンをクリックします。

==== モバイルやデスクトップを設定する
IMAP, CalDav, および CardDav はメール、連絡先、カレンダー、およびタスクをモバイルやデスクトップアプリへ同期できるオープンルールです。
{product-short} ではモバイルのプロフィールを作成し、モバイルデバイスのダウンロード、設定、および同期が可能です。

Android OS は初期から（外部アプリがない状態で）IMAP でメールの管理が可能ですが、CalDAVやCardDAVを利用するためにOpenSyncなどのアプリをインストールする必要があります。
Mac と iOS では CalDAVやCardDAVを利用できるものがありますので、MacやiOSのデバイスに追加のアプリは必要ありません。

以下にプロフィールのエクスポート方法を案内します。
モバイルデバイスへこれらのプロフィールをインポートするため、以下のヘルプの内容を参照することを推奨します。

===== プロフィールをエクスポートする
サポートしているデバイスには、5つのプロファイルのダウンロードと同期が提供しています。

メール、カレンダーとタスク、連絡先:: このプロフィールはメール、カレンダー、タスク、および連絡先をモバイルデバイスと {product-short} に同期します。
カレンダーとタスク、連絡先:: このプロフィールはカレンダー、タスク、および連絡先をモバイルデバイスと {product-short} に同期します。メールを同期しない。
カレンダーとタスク:: このプロフィールはカレンダーとタスクをモバイルデバイスと {product-short} に同期します。メールと連絡先を同期しない。
連絡先:: このプロフィールは連絡先のみをモバイルデバイスと {product-short} に同期します。メール、カレンダーとタスクを同期しない。
メール:: このプロフィールはメールのみをモバイルデバイスと {product-short} に同期します。連絡先、カレンダーとタスクを同期しない。

. image:graphics/cog.svg[cog icon, width=20] -> *設定* を選択します。
. *アカウント* をクリックし、編集するアカウントを選択します。
. *携帯またはデスクトップの設定* までスクロールします。
. ドロップダウンメニューからプロフィールを選択し、 *ダウンロード* をクリックします。
. ダウンロードするファイルの保存先を指定します。プロフィールを<<Import profiles to iOS, iOS>> や <<Import profiles to Android, Android>>へインポートする際に、{product-short} はこのファイルを必要とします。


===== iOSへプロフィールをインポートする
IMAP:: https://support.apple.com/en-in/HT201320
CalDAV:: https://support.apple.com/en-in/guide/iphone/iph3d1110d4/ios
CardDAV:: https://support.apple.com/en-in/guide/iphone/iph14a87326/ios

===== Androidへプロフィールをインポートする

Android OS は初期から（外部アプリがない状態で）IMAP のみをサポートしていますので、CalDAVやCardDAVを利用するアプリの設定詳細をご確認ください。

==== ActiveSync

. OutlookでActiveSyncを設定するには、このガイドを参照してください :- https://wiki.zimbra.com/wiki/Exchange_ActiveSync%28EAS%29_Outlook_2013

. Apple デバイスで ActiveSync を設定するには、このガイドを参照してください :- https://wiki.zimbra.com/wiki/Zimbra_Mobile_Installation_and_Setup_for_iPhone

