=== メッセージの作成
==== 送信を取り消す
*送信を取り消す* の機能使うと、送信ボタンを押した直後のメールについて、その送信リクエストを取り消すことができます。
この機能を有効にすると、メールを送信するとすぐに *取り消す* リンクが表示されます。
この通知は数秒間だけ表示されます。
通知が消えると、送信の取り消しはできなくなります。

この通知が画面に表示されている間は、メールは *下書き* フォルダに残っています。
*取り消し* をクリックすると、送信がキャンセルされたことを知らせる通知が表示され、メールは *下書き* フォルダに残ります。

. image:graphics/cog.svg[cog icon, width=20] -> *設定* を選択します。
. *メッセージの作成* から、 *送信を取り消す* の *有効* チェックボックスにチェックを追加して、この機能を有効にします。
. ページ下部のbtn:[保存]をクリックします。

==== 開封確認を要求
メールを送信する際に、受信先からメールの開封確認を常に要求することが可能です。

. image:graphics/cog.svg[cog icon, width=20] -> *設定* を選択します。
. *メッセージの作成* から、 *開封確認を要求* の *常時* チェックボックスにチェックを追加して、この機能を有効にします。
. ページ下部のbtn:[保存]をクリックします。

NOTE: メール作成中に受信者に開封確認を要求する方法については、<<mail-compose.adoc#_開封確認を要求>>をご覧ください。


==== コピーを送信済みフォルダに保存する
送信したメールのコピーを *送信済み* フォルダへ保存しないように設定することが可能です。

. image:graphics/cog.svg[cog icon, width=20] -> *設定* を選択します。
. *メッセージの作成* から、*コピーを送信済みフォルダに保存* の *有効* チェックボックスからチェックを外すことで、送信済みフォルダへメールの保存を行わないようにします。
. ページ下部のbtn:[保存]をクリックします。

==== 代行者
{product-short}を使って、他の人に自分のメールアカウントを管理させることができます。代行者は、あなたに代わってメッセージの閲覧、送信、削除ができます。
代理の人が送信したメッセージには、あなたが送信者として表示されます。

. image:graphics/cog.svg[cog icon, width=20] -> *設定* を選択します。
. *メッセージの作成* から、 *委任送信と代理送信の設定* で *代行者を追加* をクリックします。
. 代行者の名前やメールアドレスを入力します。
オートコンプリート機能では、候補が表示されますので、該当するものを選択してください。
. *委任送信* か *代理送信* のどちらで送信するかを選択します。
+
委任送信:: 代行者が完全にアカウントの所有者に _成り代わって_ 、メールを送信します。
メールの受信先では、送信者がアカウントの所有者から送信されたように見えます。
代理送信:: 代行者が _あなたの代わり_ にメールを送信します。メールの受信者は、あなたのメールアドレスだけでなく、代理人のメールアドレスも送信者として表示されます。

===== 代理送信の設定
代行者があなたとして、あるいはあなたに成り代わってメールを送信したとき、送信されたメッセージの保存先を管理することができます。

代理送信してもらったメッセージのコピーを、自分の送信済みフォルダに保存:: 代行者が送信したメールは、あなたの送信済みフォルダに入ります。
代理送信してもらったメッセージのコピーを、代理人の送信済みフォルダに保存:: 代行者が送信したメールは、代行者の送信済みフォルダに入ります。
代理送信してもらったメッセージのコピーを、代理人と自分の送信済みフォルダに保存:: 代行者が送信したメールは、あなたの送信済みフォルダに入り、さらに代行者の送信済みフォルダにも入ります。
代理送信してもらったメッセージのコピーを、保存しない:: {product-short}は、代行者が送信したメールを保存しません。
