== 設定
{product-short} の設定では、署名の登録、フィルターの作成、メールの閲覧などの機能に対する設定を変更できます。

=== 全般
このセクションでは、ストレージ、日付と時刻のフォーマット、およびログイン後に表示されるデフォルトのアプリのバージョンを扱います。

==== ストレージ
{modern-client}のこのセクションでは、{product-short}サーバーで使用中のディスク容量が表示されます。

==== 日時
{modern-client} 内で使用する日時や時間の形式を指定するオプションです。

===== 短い日付フォーマットの形式
スラッシュ又はダッシュで区切られた日付形式を設定します。 カレンダーや検索の日付け入力フォーマットなどで使用します。
日付のフォーマットは表示言語によって変わります。日本語の場合、日付のフォーマットは5種類あります:

mm/dd/yyyy:: 2021年1月9日を *01/09/2021* として表示します。
dd/mm/yyyy:: 2021年1月9日を *09/01/2021* として表示します。
yyyy-mm-dd:: 2021年1月9日を *2021-01-09* として表示します。
dd-mmm-yy:: 2021年1月9日を *2021年1月9日* として表示します。
yyyy/mm/dd:: 2021年1月9日を *2021/01/09* として表示します。

TIP: 長い日付フォーマット（年、月、日付、曜日を使ったテキストフォーマット）は、言語設定によって決まります。

===== 時刻の形式
時刻のフォーマットは4種類あります:

h:mm:: 9:21 AM を *午前9:21* として表示します。
hh:mm:: 9:21 AM を *午前09:21* として表示します。
H:MM:: 9:21 AM を *9:21* として表示します。
HH:MM:: 9:21 AM を *09:21* として表示します。

ifdef::z9[]
==== {product-short}クライアントバージョン
使用する {product-short} ウェブクライアントを選択できます。

Modern:: {modern-client} を利用します。
Classic:: {web-client} を利用します。
endif::z9[]
