=== フィルター：メール管理の自動化

{product-name} ではフィルターを作成し、受信したメールを指定したルールで自動的に配信するフォルダー別けを指定できます。

==== 新しいフィルターを作成する

. image:graphics/cog.svg[cog icon, width=20] -> *設定* をクリックします。
. 左側の *フィルター* をアクセスします。
. *フィルタを追加* をクリックし、新しいフィルターを作成します。
. *フィルター名* を入力します。
. フィルターの作成方法として、「基本」と「上級」のウィザードがあります。
デフォルトとして、新規のフィルターを作成する場合は *基本* のウィザードが開きます。

{product-name} は指定した条件に一致したメールにのみ、以下のアクションを行います。

フォルダーへ移動:: フィルターしたメールを *ジャンク* や *ゴミ* のフォルダーへも移動できます。
既読にする:: メッセージを受信トレーに残りますが、既読としてマークします。
完全に削除:: メールを完全に削除しますので、*ゴミ箱* のフォルダーへ追加しない。
転送する:: 別のメールアドレスへメールを転送します。
星印を付ける:: メールリストに目立つ星印のマークでフラグします。
タグ付き:: 作成しているタグをメールに付けます。
詳細につきましては <<mail-overview.adoc#_tags, タグ>> を参照してください。

===== 基本のウィザードを利用する
基本のウィザードでは、フィルター上限に一致したメールに1つのアクションのみを指定できます。
例えば、条件に一致したメールを既読にマークするか、ゴミ箱のフォルダーへ移動するか設定できますが、両方のアクションを実施することができません。
フィルター上限に一致しているメールに対して、複数のアクションを実施したい場合、<<Advanced, 上級モード>> をご活用ください。

. 受信したメールは *すべて* か *どれか* の条件に一致する必要があるか、指定します。
. アクションを適用する条件を指定します。
. *それから* にて、フィルター上限に一致したメールに行うアクションを選択します。
1つのアクションのみを選択できます。

===== 高級のウィザードを利用する
高級のウィザードにて、フィルター上限に一致したメールへ複数のアクションを実施することが可能です。
例えば、既読としてマークし、ゴミ箱のフォルダーへも移動できます。

. *上級に切り替える* をクリックします。
. 受信したメールは *すべて* か *どれか* の条件に一致する必要があるか、指定します。
. アクションを適用する条件を指定します。
** 条件を追加する場合、 *条件を追加* をクリックします。
. *それから* にて、フィルター上限に一致したメールに行うアクションを選択します。
1つのアクションのみを選択できます。
** アクションを追加する場合、*アクションを追加* をクリックします。

要注意：*また、追加のフィルターを処理しないでください* のチェックボックスっを有効にすると、一度フィルター条件により処理したメールが他のフィルターへ処理しないので、複数のフィルター条件に一致するメッセージを重複に処理してしまうことを回避できます。

==== フィルターを管理する
. image:graphics/cog.svg[cog icon, width=20] -> *設定* をクリックします。
. 左側の *フィルター* をアクセスします。
. 右側に作成しているすべてのフィルターがリストします。
.. image:graphics/drag.svg[2 horizontal bars icon, width=20] をクリックと上下にドラグすることで、フィルターの処理優先を変更できます。
.. フィルターにチェックマークを入れるや消すことで、フィルターの有効や無効化が可能です。
.. image:graphics/ellipsis-h.svg[3 dots menu icon, width=20] をクリックしますと、そのフィルターに対するオプション、*詳細*、 *実行する*、 *編集*、および *削除* を利用いただけます。
+
詳細:: 必要の条件をリストし、フィルター上限に一致した場合に発生するアクションを表示します。
実行する:: アカウントとフォルダーを選択し、フィルターを実行します。
編集:: フィルターを編集できる適切なウイザード（*基本* または *上級*）を開きます。
削除:: フィルターを削除します。
