=== カレンダー/リマインダー
この設定ページでは、以下を管理できます：

* イベントを作成するデフォルトのカレンダーの指定
* 週間が開始する曜日の指定
* 稼働日の開始と終了時の指定
* カレンダーイベントのタイムゾーンの指定
* カレンダーを共有した場合、携帯端末から管理の有効化設定
* イベントのリマインダーを送信するメールの宛先の指定

==== 一般のカレンダー設定について
. image:graphics/cog.svg[cog icon, width=20] -> *設定* を選択します。
. *カレンダー/リマインダー* を選択します。
. *デフォルトカレンダー* フィールドのドロップダウンメニューからデフォルトで表示するカレンダーを選択します。
 まだ <<calendar-manage-calendars.adoc#_カレンダーを追加する, カレンダーの追加>> の手順で任意のカレンダーを追加していない場合、初期のカレンダーしかないため、ドロップダウンメニューは機能しません。
. ドロップダウンメニューから *週の開始* を選択します。
. 勤務時間の開始時間を *勤務時間の開始* から選択します。
. 勤務時間の終了時間を *勤務時間の終了* から選択します。
. デフォルトのタイムゾーンを *タイムゾーン* で設定します。
.. タイムゾーンをイベント毎に設定する場合、 *イベントを作成または編集するとき* のオプションで *開始時間と終了時間のタイムゾーンを表示* へチェックを追加します。
. *共有* のオプションにて、 *CALDavクライアントに対して委任を有効にする* にチェックを追加すると、<<calendar-manage-calendars.adoc#_カレンダーを共有する, 共有したカレンダー>> に対して、管理を許可しているユーザーアカウントは携帯端末から編集を行えることを許可します。

==== イベントリマインダー
イベント開始前のリマインダー通知を受信するメールアドレスを登録することが可能です。

. image:graphics/cog.svg[cog icon, width=20] -> *設定* を選択します。
. *カレンダー/リマインダー* を選択します。
. *イベントリマインダー* で、 *リマインダーのメール送信先* のテキストボックスへ通知を受信するメールアドレスを入力します。
. ブラウザ上で通知メッセージを受けるため、 *ブラウザの通知を表示* の有効にチェックを追加します。
. イベントのリマインダーを受信する時間を *デフォルトのリマインダー時間* にて指定します。
. *期限が過ぎたイベントのリマインダーを表示* の *有効* チェックボックスにチェックを入れると、期限を過ぎた予定のリマインダーを受け取ることができます。
この機能を使うことで、見落として予定のリマインダーを受け取ることができます。

==== 予定の有無へのアクセス許可
この設定を使用して、誰があなたの空き時間やビジー状態を見ることができるかを制御することができます。
予定の主催者は、<<calendar-manage-events.adoc#_イベントを予約する, イベントを予約する>>時にbtn:[空き時間を表示]をクリックして、あなたがいつ会議に参加できるかを確認できます。

ドロップダウンからオプションを選択してください。

すべてのユーザー:: すべてのユーザーが、あなたの空いている時間や忙しい時間を見ることができます。
内部ユーザーのみ:: あなたの予定の有無に関する情報は、組織内のすべてのユーザーが見ることができます。
自分のドメインの内部ユーザーのみ:: あなたの予定の有無に関する情報は、あなたのドメイン内のユーザーのみに公開されます。他のドメインにメールアドレスを持っている組織内のユーザーは、その情報を見ることはできません。
次の内部ユーザーのみ:: このドロップダウンの下に、あなたの予定の有無に関する情報を閲覧できるユーザーのメールアドレスを入力してください。各メールアドレスを入力した後、btn:[追加]をクリックしてください。
*メールアドレスを入力* というフィールドは、このオプションでのみ有効です。
誰にも許可しない:: あなたの予定の有無に関する情報は、誰からも見えません。
