=== メールの表示
==== メールメッセージをスレッド化にする
メールへ返信する際、{product-name} がすべての返信をスレッド化し、最新のメールをスレッドの上に追加します。

件名が変更する場合、スレッドが別の新しいスレッドに割れます。

. image:graphics/cog.svg[cog icon, width=20] -> *設定* をアクセスします。
. *メールの表示* にて、*スレッドを有効にする* のチェックボックスにチェックを入力するとスレッド化を有効化できます。チェックを外しますと、スレッド化を無効化します。
. 下に *保存* をクリックします。

==== メールのスニペットを表示する
デフォルトとして、{product-name} がメールのスニペット、つまりプレビュー、を <<mail-overview.adoc#_email_pane, メールの閲覧ペイン>> で表示します。スニペットを表示したくない場合、無効化することが可能です。

. image:graphics/cog.svg[cog icon, width=20] -> *設定* をアクセスします。
. *メールの表示* にて、*スニペットを表示* のチェックボックスからチェックを外しますと、スニペットを無効化します。
. 下に *保存* をクリックします。

==== 日付でメールをグループ化する
デフォルトとして、{product-name} はメールのスレッドを日付でグループ化します。
そのため、今日、昨日、先週、などのグループ別けを閲覧できます。
この設定を無効化することができます。

. image:graphics/cog.svg[cog icon, width=20] -> *設定* をアクセスします。
. *メールの表示* にて、*日付でグループ化* のチェックボックスからチェックを外しますと、グループ化を解除します。
メールは引き続き日付で振り分けますが、グループ化しなくなります。
. 下に *保存* をクリックします。

==== メールのプレビューペインについて
{product-name} のプレビューペインは選択したメールを閲覧します。

. image:graphics/cog.svg[cog icon, width=20] -> *設定* をアクセスします。
. *メールの表示* にて、*プレビューペイン* のドロップダウンメニューをクリックします。
+
右側にプレビューペイン:: 選択したメールがメールリストの右側で表示します。
下側にプレビューペイン:: 選択したメールがメールリストの下側で表示します。
なし:: プレビューペインを無効化します。
+
. 下に *保存* をクリックします。

==== メッセージリストの密度について
この設定では、メールのリストに表示するメールメッセージの間スペースを管理できます。*スリム* が一番短い空スペース、*リラックス* が一番広い空スペースの設定となります。

. image:graphics/cog.svg[cog icon, width=20] -> *設定* をアクセスします。
. *メールの表示* にて、*メッセージリストの密度* のドロップダウンメニューをクリックし、希望の空スペースを選択します。
. 下に *保存* をクリックします。

==== メールを既読にマークする
{product-name} のデフォルト動作として、選択したメッセージを直ちに既読としてマークします。
この動作を変更する場合：

. image:graphics/cog.svg[cog icon, width=20] -> *設定* をアクセスします。
. *メールの表示* にて、*既読にする* のドロップダウンメニューをクリックします。
+
直後:: クリックで選択したメールが直ちに既読としてマークします。
2秒後:: クリックで選択したメールが *2秒後* に既読としてマークします。
5秒後:: クリックで選択したメールが *5秒後* に既読としてマークします。
なし:: クリックで選択したメールが自動的に既読としてマークせず、手動に既読としてマークする必要となります。
詳細については、<<mail-overview.adoc#_reading_pane, 閲覧ペインのツール>> を参照してください。
+
. 下に *保存* をクリックします。

==== 新規メールの確認
{product-name} が特定の期間で新規メールを確認します。
デフォルトの設定をオーバーライドすることが可能です。

. image:graphics/cog.svg[cog icon, width=20] -> *設定* をアクセスします。
. *メールの表示* にて、*新規メールの確認* ドロップダウンメニューをクリックします。
. {product-name} が新着メールを確認する期間をドロップダウンメニューから選択できます。
.. *受信トレー* の横にあるリロードアイコンをクリックすることで、新着メールを *手動で* 確認することが可能です。受信トレーの上にマウスを置きますとリロードのアイコンが表示します。
.. *新着目r-うが届いたとき* を選択すると、{product-name} が頻繁的に新着メールを確認します。
. 下に *保存* をクリックします。

==== 閲覧確認の送信
メールの送信者から閲覧確認が要求された場合、閲覧確認済み通知の送信を許可することが可能です。

{product-name} では、閲覧確認済み通知の送信を拒否するか、要求された際に {product-name} が通知を送信する許可を依頼するように設定できます。

. image:graphics/cog.svg[cog icon, width=20] -> *設定* をアクセスします。
. *メールの表示* にて、*閲覧確認* のドロップダウンメニューをクリックします。
+
確認する:: 送信者が閲覧確認を要求している場合、以下のような確認画面が表示します：

** 閲覧確認の送信を拒否する場合、image:graphics/close.svg[close icon, width=20] をクリックします。
** 閲覧確認を送信する場合、*閲覧確認の通知を送信する* をクリックします。

確認する:: このオプションでは、閲覧確認の通知を送信する前に、送信を許可する画面が表示します。
常に送信:: このオプションでは、閲覧確認の通知は必ず送信する。
送信しない:: このオプションでは、閲覧確認の通知は必ず送信しない。

. 下に *保存* をクリックします。

==== 新着メールの通知
{product-name} が新着のメールを通知する方法を選択でいます。

新しいメッセージが受信トレイに到着すると:: このオプションでは、新規メールが *受信トレイ* へのみ着信した場合、{product-name} が通知します。<<settings-filters.adoc, フィルター>> の処理により、別のフォルダーへメールを配信した場合、通知が行いません。

新しいメッセージは、任意のフォルダに到着すると:: このオプションでは、 {product-name} はメールの配信フォルダーを問わず、すべて新規に着信したメールを通知します。
