=== メッセージの表示
==== メールメッセージをスレッド表示する
メールへ返信する際、{product-short} がすべての返信をスレッド化し、最新のメールをスレッドの上に追加します。

件名が変更された場合、別の新しいスレッドにわかれます。

. image:graphics/cog.svg[cog icon, width=20] -> *設定* を選択します。
. *メッセージの表示* にて、*スレッドを有効にする* チェックボックスにチェックを入れるとスレッドを有効化できます。チェックを外すと、スレッド化が無効にされます。
. ページ下部のbtn:[保存]をクリックします。

==== メールのスニペットを表示する
デフォルトでは、{product-short}は<<mail-overview.adoc#_メールメッセージをリストするペイン, メールの閲覧ペイン>>にメッセージのスニペット(プレビュー)を表示します。スニペットが不要な場合や、受信箱が散らかって見えると感じる場合は、スニペットをオフにすることができます。

. image:graphics/cog.svg[cog icon, width=20] -> *設定* を選択します。
. *メッセージの表示* にて、*メッセージの本文先頭を表示* のチェックボックスからチェックを外すと、スニペットが無効化されます。
. ページ下部のbtn:[保存]をクリックします。

==== 日付でメールをグループ化する
{product-short}は、デフォルトでは、メールのスレッドを日付ごとにグループ化します。
そのため、_今日_、 _昨日_、 _先週_、 などのメールグループが表示されます。
この設定を無効にすることができます。

. image:graphics/cog.svg[cog icon, width=20] -> *設定* を選択します。
. *メッセージの表示* にて、*日付でグループ化* のチェックボックスからチェックを外すと、グループ化が解除されます。
メールは引き続き日付で振り分けますが、グループ化はされなくなります。
. ページ下部のbtn:[保存]をクリックします。

==== メールのプレビューウィンドウ
{product-short} のプレビューウィンドウは選択したメールを閲覧します。

. image:graphics/cog.svg[cog icon, width=20] -> *設定* を選択します。
. *メッセージの表示* にて、*プレビューウィンドウ* のドロップダウンメニューをクリックします。
+
メッセージリストの右側:: 選択したメールがメールリストの右側に表示されます。
メッセージリストの下側:: 選択したメールがメールリストの下側に表示されます。
オフ:: プレビューペインを無効化します。
+
. ページ下部のbtn:[保存]をクリックします。

==== メッセージリストの高さ
この設定では、メールのリストに表示するメールメッセージの間スペースを管理できます。*狭く表示* が一番狭いスペース、*広く表示* が一番広いスペースの設定となります。

. image:graphics/cog.svg[cog icon, width=20] -> *設定* を選択します。
. *メッセージの表示* にて、*メッセージリストの表示高さ* のドロップダウンメニューをクリックし、希望の幅を選択します。
. ページ下部のbtn:[保存]をクリックします。

==== メールを既読にマークする
{product-short} のデフォルト動作として、選択したメッセージを直ちに既読としてマークします。
この動作を変更する場合：

. image:graphics/cog.svg[cog icon, width=20] -> *設定* を選択します。
. *メッセージの表示* にて、*プレビューウィンドウに表示されてから既読に変更するまでの時間* のドロップダウンメニューをクリックします。
+
すぐに既読:: クリックで選択したメールが直ちに既読としてマークされます。
2秒後:: クリックで選択したメールが *2秒後* に既読としてマークされます。
5秒後:: クリックで選択したメールが *5秒後* に既読としてマークされます。
プレビューウィンドウに表示されたメッセージを既読にしない:: クリックで選択したメールが自動的に既読としてマークせず、手動で既読としてマークする必要があります。
詳細については、<<mail-overview.adoc#_メール閲覧のペイン, 閲覧ペイン>> を参照してください。
+
. ページ下部のbtn:[保存]をクリックします。

==== 新着メールの確認時間間隔
{product-short}は、一定の時間間隔で新しいメールをチェックします。
ただし、デフォルトの設定を上書きすることができます。

. image:graphics/cog.svg[cog icon, width=20] -> *設定* を選択します。
. *メッセージの表示* にて、*新規メールの確認* ドロップダウンメニューをクリックします。
. {product-short} が新着メールを確認する時間間隔をドロップダウンメニューから選択できます。
.. *受信箱* の横にあるリロードアイコンをクリックすることで、新着メールを *手動で* 確認することが可能です。受信箱のアイコンの上にマウスカーソルを合わせるとリロードアイコンが表示されます。
.. {product-short}が繰り返し新着メールをチェックするには、 *新着メールが届いたとき* を選択します。
. ページ下部のbtn:[保存]をクリックします。

==== 閲覧確認
メールの送信者から閲覧確認が要求された場合、閲覧確認済み通知の送信を許可することが可能です。

{product-short} では、閲覧確認済み通知の送信を拒否するか、要求された際に {product-short} が通知を送信する許可を依頼するように設定できます。

. image:graphics/cog.svg[cog icon, width=20] -> *設定* を選択します。
. *メッセージの表示* にて、*閲覧確認* のドロップダウンメニューをクリックします。
+
開封通知送信前に確認する:: 送信者が閲覧確認を要求している場合、以下のような確認画面が表示されます：

** 閲覧確認の送信を拒否する場合、image:graphics/close.svg[close icon, width=20] をクリックします。
** 閲覧確認を送信する場合、*閲覧確認の通知を送信する* をクリックします。

開封通知送信前に確認する:: このオプションでは、閲覧確認の通知を送信する前に、送信を許可する画面が表示されます。
常に開封通知を送信する:: このオプションでは、閲覧確認の通知を必ず送信します。
開封通知を送信しない:: このオプションでは、閲覧確認の通知をまったく送信しません。

. ページ下部のbtn:[保存]をクリックします。

==== 新着メール通知
{product-short}が新しいメールを通知するタイミングを選択できます。

通知しない:: {product-short} は新着メールを通知しません。

新着メッセージが受信箱に届いたとき:: このオプションを選択すると、{product-short}は、新しいメールが *受信箱* に到着したときにのみ通知します。<<settings-filters.adoc, フィルター>>により、他のフォルダに届いたメールは通知されません。

新着メッセージが任意のフォルダに届いたとき:: このオプションを選択すると、{product-short}は、新着メールが到着したフォルダに関わらず、それぞれのメールを通知します。
