=== アカウント

==== アカウントの追加
{modern-client} では、他のメールアドレスで受信したメールを管理することができます。
{modern-client} を通じて、これらのメールアドレスを使ってメールを送受信することができます。

. image:graphics/cog.svg[cog icon, width=20] -> *設定* を選択します。
. *アカウント* をクリックし、image:graphics/plus.svg[width=20] *アカウントを追加* を選択します。
. *メールアドレス* の欄にメールアドレスを入力します。
. *パスワード* 欄に、このメールアドレスのパスワードを入力します。
+
--
TIP: お使いのメールプロバイダーがアプリのパスワードの生成を義務付けている場合は、そのパスワードを生成する必要があります。
生成されたら、 *パスワード* フィールドにアプリのパスワードを使用します。
--
+
. Modern Web Appで設定するアカウントタイプを、 *POP3* または *IMAP4* から選択します。
. このメールアドレスに関連するユーザー名を入力します。
. *メールサーバー* フィールドにメールサーバー名を入力します。

この情報については、お使いのメールプロバイダーに確認してください。

ここでは、代表的なサービスプロバイダーの詳細をご紹介します。
[cols="40,40,40,40,40,40",options="header"]
|=======================================================================
|メールプロバイダ | IMAPホスト/ポート | POPホスト/ポート | SSL | アプリパスワード | "安全性の低いアプリ"設定の有効化

|Gmail
|imap.gmail.com / 993
|pop.gmail.com / 995
|必要
|不要
|必要
|=======================================================================

==== {product-short} アカウントの名前を変更する
メールを送信する際に表示する名前を指定することが可能です。

. image:graphics/cog.svg[cog icon, width=20] -> *設定* を選択します。
. *アカウント* をクリックし、編集するアカウントを選択します。
. *名前* にて、メールを送信した際に、宛先側で表示する名前を入力します。
. ページ下部のbtn:[保存]をクリックします。

// No such feature as of 4.17.0
// ==== {product-short} のメールボックス名を変更する
// {product-short} で複数のメールアカウントを設定している場合、それぞれのメールアカウントを区別させることができます。
// 
// . image:graphics/cog.svg[cog icon, width=20] -> *設定* を選択します。
// . *アカウント* をクリックし、編集するアカウントを選択します。
// . *説明* にて、アカウントを示せる名前を入力します。
// . ページ下部のbtn:[保存]をクリックします。

==== ペルソナの追加
ペルソナは、さまざまな種類のメールを管理するために、個別のメールアイデンティティを作成するのに役立ちます。
例えば、ビジネスメール用のペルソナと、個人用のペルソナを作成することができます。
ペルソナを使用すると、そのペルソナを使用して送信されるメールに、異なる *From* アドレスや *Reply-To* アドレスを指定することができます。
すべての送信メールには、使用しているペルソナのメールアドレスが表示されます。

. image:graphics/cog.svg[cog icon, width=20] -> *設定* を選択します。
. 左ペインの *アカウント* をクリックし、image:graphics/plus.svg[width=20] *ペルソナを追加* を選択します。
. ペルソナを識別するために、 *ペルソナ名* に名前を入力します。
. *このアカウントから送信* からアカウントを選択します。
 受信者が送信者の名前として認識できる名前を入力します。
+
--
TIP: このボックスが空の場合、ペルソナは送信アカウントの差出人名を使用します。
--
+
. 返信を別のメールアドレスで受信するには、「返信を別のメールアドレスに送信」の *有効* をチェックしてください。
.. _返信先アドレス_ を入力してください。
.. _返信先名_ を入力してください。
. *ペルソナを追加* をクリックして、ペルソナを作成します。

==== 2要素認証

===== 2要素認証を有効化する
管理者が2要素認証を有効にしており、かつその使用をユーザに強制していない場合、2要素認証を任意で設定することが可能です。
2要素認証の利用の有無は、ログイン後のアプリケーションの動作に影響しません。

. image:graphics/cog.svg[cog icon, width=20] -> *設定* を選択します。
. *アカウント* をクリックし、2要素認証を有効化するアカウントを選択します。
. btn:[2要素認証をセットアップ] ボタンをクリックします。
. アカウントのパスワードを入力します。
. 携帯端末に認証用のアプリをインストールします。
https://wiki.zimbra.com/wiki/TOTPApps[対応するアプリケーションのリスト] を参照してください。
. アプリのインストールが完了しましたら、携帯端末で設定します。
. {product-short} の画面にて、 *次へ* をクリックし、アカウントを認証用のアプリへ追加するプロセスを開始します。
. 認証用のアプリにて、QRコードをスキャンするか、{product-short} 画面で発行されたコードを入力します。
. *次へ* をクリックします。
. 認証用のアプリで発行したワンタイムパスワードを入力し、 *認証* をクリックすると、2要素認証の設定は完了します。

===== ログイン画面
設定完了後、{product-short} へログインする際に、一時的な認証コードも要求されます。
認証用のアプリで発行したワンタイムパスワードを入力し、 *認証* をクリックします。

===== 信頼するデバイスを追加する
2要素認証を設定後、ログインごとに認証用アプリから取得した新しいワンタイムパスワードを入力する必要があります。
ただし、特定の端末を信頼するデバイスとして設定することで、その端末からアクセスする際にワンタイムパスワードの入力が必要なくなります。

. {product-short} にアクセスします。
. ユーザー名とパスワードでログインします。
. 認証コードの入力画面にて、 *このデバイスを信頼する* にチェックを入力します。
. 認証用のアプリで発行したワンタイムパスワードを入力します。
. *認証* をクリックし、ログインします。

次回以降、この端末からログインする際には、ワンタイムパスワードを入力する必要はありません。

===== 信頼するデバイスを削除する
デバイスを信頼するデバイスのリストから外すと、その端末からログインする際に、{product-short} がワンタイムパスワードを改めて要求するようになります。
信頼するデバイスのリストからデバイスを削除する場合、まずはそのデバイスでログインします。

. image:graphics/cog.svg[cog icon, width=20] -> *設定* を選択します。
. *アカウント* をクリックし、編集するアカウントを選択します。
. *2要素認証* へスクロールします。
. *このデバイスを信頼しない* をクリックします。

TIP: 信頼するデバイスのリストから、現在ログイン中のデバイス以外のすべてのデバイスを削除する場合、 *他のすべてのデバイスを信頼しない* をクリックします。

{product-short} が直ちに信頼するデバイスリストから該当のデバイスを外します。

===== ワンタイムコードについて

認証用のアプリにアクセスできない場合、ワンタイムコードで2要素認証を完了することが可能です。
ただし、これらのコードは1回限り利用できます。
{product-short} は新しいコードを発行するオプションがあります。
2要素認証の設定後、緊急用としてこれらのコードをコピーし、安全な場所へ保管することを推奨します。

IMPORTANT: ワンタイムコードや認証用のアプリにアクセスできない場合、{product-short} へログインできません。

===== ワンタイムコードを発行する
. image:graphics/cog.svg[cog icon, width=20] -> *設定* を選択します。
. *アカウント* をクリックし、編集するアカウントを選択します。
. *2要素認証* へスクロールします。
. *未使用のコード* をクリックします。
. *クリップボードにコピー* をクリックするとコードがすべてコピーされますので、テキストファイルへ張り付けて、安全な場所に保存してください。

NOTE: *クリップボードにコピー* をクリックした後は、 *コピーしました* に変更されます。 *コピーしました* をもう一度クリックと、再びコピーできます。

==== アプリの専用パスコードを作成する
ほとんどのデスクトップアプリでは、ワンタイムコードを用いた2要素認証を行えないため、メールクライアントソフトを設定する場合、アカウントの本当のパスワードではなく、{product-short} が専用のアプリパスコードを発行し、2要素認証を回避します。

. image:graphics/cog.svg[cog icon, width=20] -> *設定* を選択します。
. *アカウント* をクリックし、編集するアカウントを選択します。
. *2要素認証* へスクロールします。
. *パスコードを追加* をクリックします。
. 作成するアプリのパスコードを特定できる名前を入力し、 *次へ* をクリックします。
. コードをコピーし、テキストファイルへ張り付けて、安全な場所に保存してください。
メーラソフトウェアを設定する際に、このコードが必要となります。
. {product-short} のメールアドレスをメーラソフトウェアに設定する際、アカウントのパスワードとしてこのパスコードを利用します。

===== アプリの専用パスコードを削除する

. image:graphics/cog.svg[cog icon, width=20] -> *設定* を選択します。
. *アカウント* をクリックし、編集するアカウントを選択します。
. *2要素認証* へスクロールします。
. 削除するパスコードの上にマウスカーソルを合わせます。
. image:graphics/close.svg[close icon, width=20] のアイコンをクリックし、パスコードを削除します。

===== 2要素認証を無効化にする

. image:graphics/cog.svg[cog icon, width=20] -> *設定* を選択します。
. *アカウント* をクリックし、編集するアカウントを選択します。
. *2要素認証* へスクロールします。
. *2要素認証を削除する* ボタンをクリックします。

上記の操作を完了後、再び追加の認証コードなしでログインが可能となります。

IMPORTANT: ご利用環境の管理者が2要素認証の無効化オプションを提供している場合のみ、無効化することが可能です。

==== 返信先アドレスを設定する
この機能でメールの返信を別のメールアドレスへ受信するように設定できます。

. image:graphics/cog.svg[cog icon, width=20] -> *設定* を選択します。
. *アカウント* をクリックし、編集するアカウントを選択します。
. *返信先アドレス* へスクロールします。
. *返信を別のメールアドレスに送信* のチェックボックスにチェックを入力します。
. 送信したメールの返信先メールアドレスを入力します。
. 入力したメールアドレスに関連する名前を入力します。
. ページ下部のbtn:[保存]をクリックします。

==== 別の場所でメールをアクセスする
{product-short} に転送先のアドレスを設定することが可能です。{product-short} は指定した転送先アドレスへ、すべてのメールを転送します。

. image:graphics/cog.svg[cog icon, width=20] -> *設定* を選択します。
. *アカウント* をクリックし、編集するアカウントを選択します。
. *転送設定* へスクロールします。
. *指定したアドレスにメールを転送する* のチェックボックスにチェックを入力します。
. 転送先のメールアドレスを入力し、 *追加* ボタンをクリックします。
. メールを転送した後、{product-short} にもコピーを保管する場合、 *メッセージのコピーを保存する* のチェックボックスにチェックを入力します。

. ページ下部のbtn:[保存]をクリックします。

ifdef::Desktop_app[]
==== PSTファイルをインポートする
NOTE: この機能はWindows用の{product-short}デスクトップアプリでのみ提供しています。

メールアカウントをOutlookへ追加する場合、{product-short} がメールメッセージ、カレンダー情報、連絡先、およびタスクのローカルコピーを保存します。
多少のアカウントは Outlook データファイル (`.pst` ファイル）に情報を保存します。

これらの `PST` は {product-short} のデスクトップアプリに <<mail-localstorage.adoc#_ローカルストレージ, ローカルストレージ>> のフォルダへインポートすることが可能です。
以下の手順では、該当の `PST` ファイルは既にコンピュータ上にコピーしていることを前提しています。
メール、連絡先、およびカレンダーを `PST` ファイルとしてエクスポートやバックアップする場合、https://support.office.com/en-us/article/back-up-your-email-e5845b0b-1aeb-424f-924c-aa1c33b18833[Back up your email] を参照してください。

. image:graphics/cog.svg[cog icon, width=20] -> *設定* を選択します。
. *アカウント* をクリックし、編集するアカウントを選択します。
. *Import from Outlook (.pst file)* までスクロールします。
. *Choose .pst file* をクリックします。
. インポートする `PST` を選択します。
. *Import* をクリックします。

NOTE: {product-short}が`PST`をインポートしているあいだ、ローカルフォルダにアクセスできません。
*メール* は引き続き使用できますが、*カレンダー* と *連絡先* は使用できません。インポートが完了すると{product-short}が通知します。
endif::Desktop_app[]

==== データをエクスポートする
すべてのメール、連絡先、およびカレンダーを `.tgz` ファイルとしてエクスポートすることが可能です。
特定のフォルダ、メールメッセージ、連絡先、またはカレンダーをエクスポートする場合、それらのアイテムを右クリックし、メニューから *エクスポート* を選択します。

. image:graphics/cog.svg[cog icon, width=20] -> *設定* を選択します。
. *アカウント* をクリックし、編集するアカウントを選択します。
. 画面をスクロールし、btn:[エクスポート] ボタンをクリックします。

==== データをインポートする
`.tgz` ファイルからすべてのメール、連絡先、およびカレンダーをインポートすることが可能です。

. image:graphics/cog.svg[cog icon, width=20] -> *設定* を選択します。
. *アカウント* をクリックし、編集するアカウントを選択します。
. *インポート* へスクロールし、btn:[インポート] ボタンをクリックします。

==== モバイルやデスクトップを設定する
IMAP、 CalDav、 および CardDav はメール、連絡先、カレンダー、およびタスクをモバイルやデスクトップアプリへ同期できるオープンルールです。
{product-short} ではモバイルのプロファイルを作成し、モバイルデバイスのダウンロード、設定、および同期が可能です。

Android OS は初期から（外部アプリがない状態で）IMAP でメールの管理が可能ですが、CalDAVやCardDAVを利用するためにOpenSyncなどのアプリをインストールする必要があります。
Mac と iOS では CalDAVやCardDAVを利用できるものがありますので、MacやiOSのデバイスに追加のアプリは必要ありません。

ここでは、プロファイルのエクスポート方法を説明します。
モバイルデバイスへこれらのプロファイルをインポートするため、以下のヘルプの内容を参照することを推奨します。

===== プロファイルをエクスポートする
デバイスと同期するために使用できるプロファイルが5つあります。

メール、カレンダーとタスク、連絡先:: このプロファイルは、モバイルデバイス上のメール、カレンダー、タスク、および連絡先を {product-short}と同期します。
カレンダーとタスク、連絡先:: このプロファイルは、{product-short} を使って、モバイルデバイス上のカレンダー、タスク、連絡先のみを同期し、メールは同期しません。
カレンダーとタスク:: このプロファイルは、モバイルデバイス上のカレンダーとタスクのみを{product-short}で同期し、メールや連絡先は同期しません。
連絡先:: このプロファイルは、モバイルデバイス上の連絡先のみを{product-short}と同期し、メール、カレンダー、タスクは同期しません。
メール:: このプロファイルでは、{product-short}を使用して、モバイルデバイス上のメールのみを同期し、連絡先、カレンダー、タスクは同期しません。

. image:graphics/cog.svg[cog icon, width=20] -> *設定* を選択します。
. *アカウント* をクリックし、編集するアカウントを選択します。
. *携帯またはデスクトップの設定* までスクロールします。
. ドロップダウンメニューからプロファイルを選択し、 *ダウンロード* をクリックします。
. ダウンロードするファイルの保存先を指定します。プロファイルを<<_iOSへプロファイルをインポートする, iOS>> や <<_Androidへプロファイルをインポートする, Android>>へインポートする際に、{product-short} はこのファイルを必要とします。


===== iOSへプロファイルをインポートする
IMAP:: https://support.apple.com/ja-jp/HT201320
CalDAV:: https://support.apple.com/ja-jp/guide/iphone/iph3d1110d4/ios
CardDAV:: https://support.apple.com/ja-jp/guide/iphone/iph14a87326/ios

===== Androidへプロファイルをインポートする

外部アプリを使わない限り、Androidでは、IMAPのみの対応となりますので、CardDAV、CalDAVについては、お使いのアプリの説明をご確認ください。

==== ActiveSync

. OutlookでActiveSyncを設定するには、このガイドを参照してください :- https://wiki.zimbra.com/index.php?title=Exchange_ActiveSync(EAS)_Outlook_2013

. Apple デバイスで ActiveSync を設定するには、このガイドを参照してください :- https://wiki.zimbra.com/wiki/Zimbra_Mobile_Installation_and_Setup_for_iPhone

