=== アカウント設定
==== {product-name} アカウントの名前を変更する
メールを送信する際に表示する名前を指定することが可能です。

. image:graphics/cog.svg[cog icon, width=20] -> *設定* をアクセスします。
. 左側に *アカウント* をクリックし、右側で編集するアカウントを選択します。
. *お名前* にて、メールを送信した際に、宛先側で表示する名前を入力します。
. 画面の下に *保存* をクリックします。

==== {product-name} のメールボックス名を変更する
複数のメールアカウントを {product-name} に設定している場合、各アカウントを個別に利用できるようにしh多い場合があります。

. image:graphics/cog.svg[cog icon, width=20] -> *設定* をアクセスします。
. 左側に *アカウント* をクリックし、右側で編集するアカウントを選択します。
. *説明* にて、アカウントを示せる名前を入力します。
. 画面の下に *保存* をクリックします。

==== 二要素認証
アカウントに二要素認証（2FA）を有効化や無効化するオプションが提供している可能性があります。

===== 2FA を有効化する
管理者が二要素認証を有効化しているが、強制的に運用していない場合、二要素認証を任意で設定することが可能です。
設定しない場合、アプリケーションの動作が変わりません。

. image:graphics/cog.svg[cog icon, width=20] -> *設定* をアクセスします。
. 左側に *アカウント* をクリックし、右側で2FAを有効化するアカウントを選択します。
. btn:[Set up two-factor authentication] のボタンをクリックします。
. アカウントのパスワードを入力します。
. *二要素認証を設定する* をクリックします。
. ご利用中の携帯端末に認証用のアプリをインストールします。
https://wiki.zimbra.com/wiki/TOTPApps[対応するアプリケーションのリスト] を参照してください。
. アプリのインストールが完了しましたら、携帯端末で設定します。
. {product-name} の画面にて、*次へ* をクリックし、アカウントを認証用のアプリへ追加するプロセスを開始します。
. 認証用のアプリにて、QRコードをスキャンするか、{product-name} 画面で発行されたコードを入力します。
. *次へ* をクリックします。
. 認証用のアプリで発行した一時コードを入力し、*認証* をクリックすることで、二要素認証の設定を完了します。

===== ログイン画面
設定完了後、{product-name} へログインする際に、一時的な認証コードも要求します。
認証用のアプリで発行した一時コードを入力し、*認証* をクリックします。
ご利用中のアカウントに二要素認証が有効の状態となっています。

===== 信頼するデバイスを追加する
2FAを設定後、{product-name} は毎ログインで認証用のアプリから新しい認証コードを入力する必要となります。
ただし、特定の端末を信頼するデバイスとして設定することで、その端末からアクセスする際に認証コードの入力が必要なくなります。

. {product-name} をアクセスします。
. ユーザー名とパスワードでログインします。
. 認証コードの入力画面にて、*子のデバイスを信頼する* にチェックを入力します。
. 認証用のアプリで発行した一時コードを入力します。
. 、*認証* をクリックし、ログインします。

次回、同じ端末からログインする際に認証コードの入力が必要しなくなります。

===== 信頼するデバイスを削除する
デバイスを信頼するデバイスのリストから外す場合、その端末からログインする際に、{product-name} が認証コードを改めて要求するように戻ります。
信頼するデバイスのリストからデバイスを削除する場合、まずはそのデバイスでログインします。

. image:graphics/cog.svg[cog icon, width=20] -> *設定* をアクセスします。
. 左側に *アカウント* をクリックし、右側で編集するアカウントを選択します。
. *二要素認* の場所へスクロールします。
. *このデバイスを信頼しないでください* をクリックします。

メモ：信頼するデバイスのリストから、現在にログイン中のデバイス以外、他のデバイスをすべて削除する場合、*他のすべてのデバイスを無効にする* をクリックします。

{product-name} が直ちに信頼するデバイスリストから該当のデバイスを外します。

===== ワンタイムコードについて

認証用のアプリをアクセスできない場合、ワンタイムコードで二要素認を完了することが可能です。
ただし、これらのコードは1回限りご利用いただけます。
{product-name} は新しいコードを発行するオプションはあります。
二要素認証の設定後、緊急用としてこれらのコードをコピーし、安全な場所へ保管することを推奨します。

要注意：ワンタイムコードや認証用のアプリをアクセスできない場合、{product-name} へログインできません。

===== ワンタイムコードを発行する
. image:graphics/cog.svg[cog icon, width=20] -> *設定* をアクセスします。
. 左側に *アカウント* をクリックし、右側で編集するアカウントを選択します。
. *二要素認証* の場所へスクロールします。
. *未使用コード10* をクリックします。
. *クリップボードにコピー* をクリックするとコードをすべてコピーしますので、テキストファイルへ張り付けて、安全な場所に保存してください。

注意：*クリップボードにコピー* をクリックした後、*コピーしました* に変更します。*コピーしました* を改めてクリックすることで、再びコピーできます。

==== アプリの専用パスコードを作成する
ほとんどのデスクトップアプリでは二要素認証を行える一時コードの認証方法がありませんので、メーラソフトを設定する場合、アカウントの本当のパスワードではなく、{product-name} が専用のアプリパスコードを発行し、二要素認証を回避します。

. image:graphics/cog.svg[cog icon, width=20] -> *設定* をアクセスします。
. 左側に *アカウント* をクリックし、右側で編集するアカウントを選択します。
. *二要素認証* の場所へスクロールします。
. *パスコードを追加* をクリックします。
. 作成するアプリのパスコードを特定できる名前を入力し、*次へ* をクリックします。
. コードをコピーし、テキストファイルへ張り付けて、安全な場所に保存してください。
メーラソフトウェアを設定する際に、このコードがアカウントのパスワードとして入力する必要があります。
. {product-name} のメールアドレスをメーラソフトウェアに設定する際、アカウントのパスワード入力する際に、このパスコードを利用します。

===== アプリの専用パスコードを削除する

. image:graphics/cog.svg[cog icon, width=20] -> *設定* をアクセスします。
. 左側に *アカウント* をクリックし、右側で編集するアカウントを選択します。
. *二要素認証* の場所へスクロールします。
. 削除するパスコードの上にマウスを置きます。
. image:graphics/close.svg[close icon, width=20] のアイコンをクリックし、パスコードを削除します。

===== 2FA を無効化にする

. image:graphics/cog.svg[cog icon, width=20] -> *設定* をアクセスします。
. 左側に *アカウント* をクリックし、右側で編集するアカウントを選択します。
. *二要素認証* の場所へスクロールします。
. *二要素認証を削除する* のボタンをクリックします。

上記の操作を完了後、再び追加の認証コードなしでログインが可能となります。

要注意：ご利用環境の管理者が 2FA の無効化オプションを提供している場合のみ、無効化することが可能です。

==== 返信先アドレスを設定する
この機能でメールの返信を別のメールアドレスへ受信するように設定いただけます。

. image:graphics/cog.svg[cog icon, width=20] -> *設定* をアクセスします。
. 左側に *アカウント* をクリックし、右側で編集するアカウントを選択します。
. *返信先アドレス* へスクロールします。
. *送信したメールに対する返信を別のアドレスで受信します。* のチェックボックスにチェックを入力します。
. 送信したメールの返信先メールアドレスを入力します。
. 入力したメールアドレスに関連する名前を入力します。
. 画面の下に *保存* をクリックします。

==== 別の場所でメールをアクセスする
{product-name} に転送先のアドレスを設定することが可能です。{product-name} が指定した転送先アドレスへすべてのメールを転送します。

. image:graphics/cog.svg[cog icon, width=20] -> *設定* をアクセスします。
. 左側に *アカウント* をクリックし、右側で編集するアカウントを選択します。
. *別の場所でメールにアクセス* へスクロールします。
. *転送：メールは指定されたアドレスに転送されるため、そこで確認できます。* のチェックボックスにチェックを入力します。
. 転送先のメールアドレスを入力し、*追加* のボタンをクリックします。
. メールを転送した後、{product-name} にもコピーを保管する場合、*ここにコピーを保管してください。* のチェックボックスにチェックを入力します。

. 画面の下に *保存* をクリックします。

ifdef::Desktop_app[]
==== PSTファイルをインポートする
ご注意：この機能はWindows用の{product-name}デスクトップアプリでのみ提供しています。

メールアカウントをOutlookへ追加する場合、{product-name} がメールメッセージ、カレンダー情報、連絡先、およびタスクのローカルコピーを保存します。
多少のアカウントは Outlook データファイル (`.pst` ファイル）に情報を保存します。

これらの `PST` は {product-name} のデスクトップアプリに <<mail-localstorage.adoc#_local_storage, ローカルストレージ>> のフォルダーへインポートすることが可能です。
以下の手順では、該当の `PST` ファイルは既にコンピューター上にコピーしていることを前提しています。
メール、連絡先、およびカレンダーを `PST` ファイルとしてエクスポートやバックアップする場合、https://support.office.com/en-us/article/back-up-your-email-e5845b0b-1aeb-424f-924c-aa1c33b18833[Back up your email] を参照してください。

. image:graphics/cog.svg[cog icon, width=20] -> *設定* をアクセスします。
. 左側に *アカウント* をクリックし、右側で編集するアカウントを選択します。
. *Import from Outlook (.pst file)* までスクロールします。
. *Choose .pst file* をクリックします。
. インポートする `PST` を選択します。
. *Import* をクリックします。

ご注意：{product-name} が `PST` ファイルのインポート中にローカルフォルダーをアクセスでいません。
*メール*を継続に利用いただけますが、*カレンダー* や *連絡先* を利用しないでください。インポートが完了しました、{product-name} が通知します。
endif::Desktop_app[]

==== データをエクスポートする
すべてのメール、連絡先、およびカレンダーを `.tgz` ファイルとしてエクスポートすることが可能です。
特定のフォルダー、メールメッセージ、連絡先、またはカレンダーをエクスポートする場合、それらのアイテムを右クリックし、メニューから *輸出する* を選択します。

. image:graphics/cog.svg[cog icon, width=20] -> *設定* をアクセスします。
. 左側に *アカウント* をクリックし、右側で編集するアカウントを選択します。
. *輸出する* へスクロールし、btn:[輸出する] のボタンをクリックします。

==== データをインポートする
`.tgz` ファイルからすべてのメール、連絡先、およびカレンダーをインポートすることが可能です。

. image:graphics/cog.svg[cog icon, width=20] -> *設定* をアクセスします。
. 左側に *アカウント* をクリックし、右側で編集するアカウントを選択します。
. *インポート* へスクロールし、btn:[インポート] のボタンをクリックします。

==== モバイルやデスクトップを設定する
IMAP, CalDav, および CardDav はメール、連絡先、カレンダー、およびタスクをモバイルやデスクトップアプリへ同期できるオープンルールです。
{product-name} ではモバイルのプロフィールを作成し、モバイルデバイスのダウンロード、設定、および同期が可能です。

Android OS は初期から（外部アプリがない状態で）IMAP でメールの管理が可能ですが、CalDAVやCardDAVを利用するためにOpenSyncなどのアプリをインストールする必要があります。
Mac と iOS では CalDAVやCardDAVを利用できるものがありますので、MacやiOSのデバイスに追加のアプリは必要ありません。

以下にプロフィールのエクスポート方法を案内します。
モバイルデバイスへこれらのプロフィールをインポートするため、以下のヘルプの内容を参照することを推奨します。

===== プロフィールをエクスポートする
サポートしているデバイスには、5つのプロファイルのダウンロードと同期が提供しています。

メール、カレンダーとタスク、連絡先:: このプロフィールはメール、カレンダー、タスク、および連絡先をモバイルデバイスと {product-name} に同期します。
カレンダーとタスク、連絡先:: このプロフィールはカレンダー、タスク、および連絡先をモバイルデバイスと {product-name} に同期します。メールを同期しない。
カレンダーとタスク:: このプロフィールはカレンダーとタスクをモバイルデバイスと {product-name} に同期します。メールと連絡先を同期しない。
連絡先:: このプロフィールは連絡先のみをモバイルデバイスと {product-name} に同期します。メール、カレンダーとタスクを同期しない。
メール:: このプロフィールはメールのみをモバイルデバイスと {product-name} に同期します。連絡先、カレンダーとタスクを同期しない。

. image:graphics/cog.svg[cog icon, width=20] -> *設定* をアクセスします。
. 左側に *アカウント* をクリックし、右側で編集するアカウントを選択します。
. *携帯またはデスクトップの設定* までスクロールします。
. ドロップダウンメニューからプロフィールを選択し、*ダウンロード* をクリックします。
. ダウンロードするファイルの保存先を指定します。プロフィールを<<Import profiles to iOS, iOS>> や <<Import profiles to Android, Android>>へインポートする際に、{product-name} がこのファイルを必要としてます。


===== iOSへプロフィールをインポートする
IMAP:: https://support.apple.com/en-in/HT201320
CalDAV:: https://support.apple.com/en-in/guide/iphone/iph3d1110d4/ios
CardDAV:: https://support.apple.com/en-in/guide/iphone/iph14a87326/ios

===== Androidへプロフィールをインポートする

Android OS は初期から（外部アプリがない状態で）IMAP のみをサポートしていますので、CalDAVやCardDAVを利用するアプリの設定詳細をご確認ください。
