=== フィルター：メール管理の自動化

{product-short}では、いくつかのルールを定義することで、受信したメッセージをフォルダに分類するフィルタを作成することができます。

==== 新しいフィルターを作成する

. image:graphics/cog.svg[cog icon, width=20] -> *設定* を選択します。
. *フィルター* を選択します。
. *フィルタを追加* をクリックし、新しいフィルターを作成します。
. *フィルター名* を入力します。
. フィルターの作成方法として、「基本」と「詳細」のウィザードがあります。
デフォルトとして、新規のフィルターを作成する場合は *基本* のウィザードが開きます。

{product-short} は指定した条件に一致したメールにのみ、以下のアクションを行います。

フォルダへ移動:: フィルターしたメールを *迷惑メール* や *ゴミ箱* フォルダなどへ移動させます。
既読にする:: メッセージは受信箱に残りますが、既読としてマークされます。
完全に削除:: メールを完全に削除します。*ゴミ箱* のフォルダには移動されません。
アドレスにリダイレクト:: 別のメールアドレスへメールをリダイレクトします。
スターを付ける:: メールリストにスターのマークでフラグを付けます。
つぎのタグをつける:: 既に作成されているタグをメールに付けます。
詳細につきましては <<mail-overview.adoc#_タグ, タグ>> を参照してください。

===== 基本ウィザードを利用する
基本のウィザードでは、フィルタ条件を満たすメールに対して、1つのアクションしか指定できません。
例えば、既読にするか、ゴミ箱に移動するかだけで、両方を行うことはできません。
特定の条件に一致するメールに複数のアクションを実行するには、 <<_詳細ウィザードを利用する, 詳細に切り替える>> を使ってください。

. 受信したメールは *すべて* か *どれか* の条件に一致する必要があるか、指定します。
. アクションを適用する条件を指定します。
. *次に* で、フィルタリングされたメールをどうするかを選択します。
1つのアクションのみを選択できます。

===== 詳細ウィザードを利用する
詳細ウィザードでは、フィルタ条件を満たしたメールに影響を与える複数のアクションを指定できます。
例えば、既読としてマークして、ゴミ箱に移動させることができます。

. *詳細に切り替える* をクリックします。
. 受信したメールは *すべて* か *どれか* の条件に一致する必要があるか、指定します。
. アクションを適用する条件を指定します。
** 条件を追加する場合、 *条件を追加* をクリックします。
. *次に* で、フィルタリングされたメールをどうするかを選択します。
1つのアクションのみを選択できます。
** アクションを追加する場合、 *アクションを追加* をクリックします。

IMPORTANT: *その他のフィルターは処理しない* のチェックボックスを有効にすると、複数のフィルターの条件を満たすメッセージに対して、他のフィルターを実行しないようにします。

==== フィルターを管理する
. image:graphics/cog.svg[cog icon, width=20] -> *設定* を選択します。
. *フィルター* を選択します。
. 作成しているすべてのフィルターがリストで表示されます。
.. image:graphics/drag.svg[2 horizontal bars icon, width=20] をクリック＆ドラッグして、フィルターの優先順位を上げたり下げたりすることができます。
.. フィルターにチェックを入れたり外したりして、有効にしたり無効にしたりします。
.. 各フィルターの横の image:graphics/ellipsis-h.svg[3 dots menu icon, width=20] をクリックすると、 *詳細* 、 *実行* 、 *編集* 、 *削除* オプションが表示されます。
+
詳細:: メールが満たすべき条件と、メールがフィルター条件を満たしたときのアクションを一覧表示します。
実行:: アカウントを選択し、フィルタを実行するフォルダを選択します。
編集:: フィルターを編集するためのエディタ（ *基本* または *詳細* ）を開きます。
削除:: フィルターを削除する前に確認ダイアログを表示します。
